(() => {
  const E=window.DosageEngine;if(!E)throw new Error('DosageEngine not loaded');
  const typeEl=document.querySelector('#type'),difficultyEl=document.querySelector('#difficulty'),varsEl=document.querySelector('#variables'),problemEl=document.querySelector('#problem'),answerEl=document.querySelector('#answer-panel'),labelEl=document.querySelector('#type-label'),formulaEl=document.querySelector('#formula-panel'),formulaBtn=document.querySelector('#show-formula');
  let current=null;
  E.types.forEach(t=>typeEl.add(new Option(t.label,t.key)));
  const labels={drug:'Medication',context:'Clinical context',order:'Ordered dose/rate',have:'Available dose/concentration',qty:'Available quantity (mL or units)',unit:'Quantity unit',route:'Route/frequency',kg:'Weight (kg)',dose:'Dose per kg',freq:'Frequency',doses:'Doses per day',minDay:'Minimum mg/kg/day',maxDay:'Maximum mg/kg/day',volume:'Volume (mL)',hours:'Time (hours)',minutes:'Time (minutes)',fluid:'IV fluid',rate:'Rate (mL/hr)',start:'Start time (24-hour)',v:'Volume (mL)',r:'Rate (mL/hr)',dropFactor:'Drop factor (gtt/mL)',dropsPerMinute:'Flow (gtt/min)',conc:'Concentration',bagUnits:'Bag total units',bagMl:'Bag volume (mL)',bagMcg:'Bag total mcg',bagAmt:'Bag total amount',orderUnit:'Order unit',kind:'Scenario type',daily:'Daily dose (mg/kg/day)'};
  const editableSkip=new Set(['min','max','ml','safety']);
  function pretty(k){return labels[k]||k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
  function renderFields(vars){varsEl.innerHTML='';Object.entries(vars||{}).filter(([k])=>!editableSkip.has(k)).forEach(([k,v])=>{const lab=document.createElement('label');lab.textContent=pretty(k);const input=document.createElement('input');input.dataset.key=k;input.value=v;input.type=typeof v==='number'?'number':'text';if(typeof v==='number')input.step='any';lab.appendChild(input);varsEl.appendChild(lab)})}
  function readVars(){const out={...(current?.vars||{})};varsEl.querySelectorAll('[data-key]').forEach(input=>{const k=input.dataset.key,outVal=input.type==='number'?Number(input.value):input.value;out[k]=outVal});return out}
  function round(n,p=1){return E.round(n,p)}
  function rebuild(key,v){
    if(key==='basic-dose'){const a=round(v.order/v.have*v.qty,2);return{...current,vars:v,answer:a,unit:v.unit,prompt:`A patient has an order for ${v.drug} ${v.order} mg ${v.route}. Available: ${v.have} mg per ${v.qty} ${v.unit}. How many ${v.unit} should the nurse administer?`,formula:'Desired dose ÷ dose on hand × quantity = amount to give',solution:`(${v.order} mg ÷ ${v.have} mg) × ${v.qty} ${v.unit} = ${a} ${v.unit}`}}
    if(key==='weight-dose'){const a=round(v.kg*v.dose,1);return{...current,vars:v,answer:a,unit:'mg',prompt:`A ${v.kg}-kg patient is prescribed ${v.drug} ${v.dose} mg/kg/dose ${v.route}. How many mg should the patient receive per dose?`,formula:'mg/kg/dose × kg = mg per dose',solution:`${v.dose} × ${v.kg} = ${a} mg/dose`}}
    if(key==='peds-safe-range'){const min=round(v.kg*v.minDay/v.doses,1),max=round(v.kg*v.maxDay/v.doses,1),safety=v.order<min?'too low':v.order>max?'too high':'safe',ml=round(v.order*v.qty/v.have,1),nv={...v,min,max,ml,safety};return{...current,vars:nv,answer:safety,unit:'',prompt:`A child weighs ${v.kg} kg${v.context?` and is being treated for a ${v.context}`:''}. The provider orders ${v.drug} ${v.order} mg PO ${v.freq}. Recommended: ${v.minDay}–${v.maxDay} mg/kg/day in equally divided doses. Available: ${v.have} mg/${v.qty} mL. Is the ordered dose safe, too low, or too high?`,formula:'mg/kg/day × kg ÷ doses/day = safe mg/dose range',solution:`Safe range: ${min}–${max} mg/dose. Order ${v.order} mg is ${safety}.${safety==='safe'?` Amount: (${v.order} ÷ ${v.have}) × ${v.qty} = ${ml} mL.`:''}`}}
    if(key==='mlhr-hours'){const a=round(v.volume/v.hours,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`${v.fluid||'IV fluid'}, ${v.volume} mL, is prescribed to infuse over ${v.hours} hours. What rate should the IV pump be programmed to?`,formula:'mL ÷ hours = mL/hr',solution:`${v.volume} ÷ ${v.hours} = ${a} mL/hr`}}
    if(key==='mlhr-minutes'){const a=round(v.volume/(v.minutes/60),1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`${v.drug||'Medication'} in ${v.volume} mL IV is ordered to infuse over ${v.minutes} minutes. What pump rate is required?`,formula:'mL ÷ (minutes ÷ 60) = mL/hr',solution:`${v.minutes} ÷ 60 = ${round(v.minutes/60,2)} hr; ${v.volume} ÷ ${round(v.minutes/60,2)} = ${a} mL/hr`}}
    if(key==='infusion-time'){const a=round(v.volume/v.rate,2);return{...current,vars:v,answer:a,unit:'hours',prompt:`${v.fluid||'IV fluid'}, ${v.volume} mL, is infusing at ${v.rate} mL/hr. How many hours will the infusion take?`,formula:'mL ÷ mL/hr = hours',solution:`${v.volume} ÷ ${v.rate} = ${a} hr`}}
    if(key==='completion-time'){const [h,m]=String(v.start).split(':').map(Number),mins=Math.round(v.v/v.r*60),end=(h*60+m+mins)%1440,ans=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;return{...current,vars:v,answer:ans,unit:'',prompt:`${v.fluid||'IV fluid'}, ${v.v} mL, starts at ${v.start} and infuses at ${v.r} mL/hr. Using 24-hour time, when will it finish?`,formula:'Find infusion duration, then add it to the start time',solution:`${v.v} ÷ ${v.r} = ${round(v.v/v.r,2)} hr ≈ ${mins} min; ${v.start} + ${mins} min = ${ans}`}}
    if(key==='gtt-volume-time'){const a=Math.round(v.volume*v.dropFactor/(v.hours*60));return{...current,vars:v,answer:a,unit:'gtt/min',prompt:`${v.fluid||'IV fluid'}, ${v.volume} mL, is prescribed over ${v.hours} hours using tubing with a drop factor of ${v.dropFactor} gtt/mL. Calculate gtt/min.`,formula:'(mL × gtt/mL) ÷ total minutes = gtt/min',solution:`(${v.volume} × ${v.dropFactor}) ÷ (${v.hours} × 60) = ${a} gtt/min`}}
    if(key==='gtt-from-mlhr'){const a=Math.round(v.rate*v.dropFactor/60);return{...current,vars:v,answer:a,unit:'gtt/min',prompt:`${v.fluid||'IV fluid'} is infusing at ${v.rate} mL/hr using tubing with a drop factor of ${v.dropFactor} gtt/mL. What gravity flow rate should be set?`,formula:'(mL/hr × gtt/mL) ÷ 60 = gtt/min',solution:`(${v.rate} × ${v.dropFactor}) ÷ 60 = ${a} gtt/min`}}
    if(key==='mlhr-from-gtt'){const a=round(v.dropsPerMinute*60/v.dropFactor,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`${v.fluid||'IV fluid'} is running at ${v.dropsPerMinute} gtt/min through tubing with a drop factor of ${v.dropFactor} gtt/mL. What is the equivalent mL/hr rate?`,formula:'(gtt/min × 60) ÷ gtt/mL = mL/hr',solution:`(${v.dropsPerMinute} × 60) ÷ ${v.dropFactor} = ${a} mL/hr`}}
    if(key==='reconstitution'){const a=round(v.order/v.conc,2);return{...current,vars:v,answer:a,unit:'mL',prompt:`After reconstitution, ${v.drug} is labeled ${v.conc} mg/mL. The provider orders ${v.order} mg. How many mL should the nurse withdraw from the reconstituted vial?`,formula:'ordered mg ÷ final concentration (mg/mL) = mL',solution:`${v.order} ÷ ${v.conc} = ${a} mL`}}
    if(key==='units-hour'){const conc=v.bagUnits/v.bagMl,a=round(v.order/conc,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`A patient is receiving ${v.drug} at ${v.order} units/hr. The IV contains ${v.bagUnits} units in ${v.bagMl} mL. What pump rate is required?`,formula:'ordered units/hr ÷ concentration (units/mL) = mL/hr',solution:`${v.bagUnits} ÷ ${v.bagMl} = ${round(conc,2)} units/mL; ${v.order} ÷ ${round(conc,2)} = ${a} mL/hr`}}
    if(key==='mcg-minute'){const conc=v.bagMcg/v.bagMl,a=round(v.order*60/conc,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`A patient is prescribed ${v.drug} ${v.order} mcg/min. The IV contains ${v.bagMcg} mcg in ${v.bagMl} mL. What pump rate is required?`,formula:'(mcg/min × 60) ÷ mcg/mL = mL/hr',solution:`${v.order} × 60 = ${v.order*60} mcg/hr; ÷ ${round(conc,2)} mcg/mL = ${a} mL/hr`}}
    if(key==='mcg-kg-minute'){const conc=v.bagMcg/v.bagMl,a=round(v.dose*v.kg*60/conc,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`A ${v.kg}-kg patient is prescribed ${v.drug} ${v.dose} mcg/kg/min. The IV contains ${v.bagMcg} mcg in ${v.bagMl} mL. What pump rate is required?`,formula:'(mcg/kg/min × kg × 60) ÷ mcg/mL = mL/hr',solution:`${v.dose} × ${v.kg} × 60 ÷ ${round(conc,2)} = ${a} mL/hr`}}
    if(key==='amount-hour'){if(v.drug==='amiodarone'){const hourly=v.order*60,conc=v.bagAmt/v.bagMl,a=round(hourly/conc,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`Amiodarone is ordered at ${v.order} mg/min. The IV contains ${v.bagAmt} mg in ${v.bagMl} mL. What pump rate is required?`,formula:'(mg/min × 60) ÷ mg/mL = mL/hr',solution:`${v.order} × 60 = ${hourly} mg/hr; ÷ ${round(conc,2)} mg/mL = ${a} mL/hr`}}const conc=v.bagAmt/v.bagMl,a=round(v.order/conc,1);return{...current,vars:v,answer:a,unit:'mL/hr',prompt:`Magnesium sulfate is ordered at ${v.order} g/hr by continuous IV infusion. The IV contains ${v.bagAmt} g in ${v.bagMl} mL. What pump rate is required?`,formula:'ordered g/hr ÷ concentration (g/mL) = mL/hr',solution:`${v.order} ÷ ${round(conc,4)} = ${a} mL/hr`}}
    if(key==='meq-ml'){const a=round(v.order/v.conc,1),prompt=v.kind==='additive'?`The provider orders ${v.drug} ${v.order} mEq to be added to a compatible IV solution. The concentrate contains ${v.conc} mEq/mL. How many mL of concentrate should be withdrawn for the admixture?`:`The provider orders ${v.drug} ${v.order} mEq IV. The solution contains ${v.conc} mEq/mL. How many mL contain the ordered dose?`;return{...current,vars:v,answer:a,unit:'mL',prompt,formula:'ordered mEq ÷ concentration (mEq/mL) = mL',solution:`${v.order} ÷ ${v.conc} = ${a} mL`}}
    if(key==='daily-divided'){const day=round(v.daily*v.kg,1),a=round(day/v.doses,1);return{...current,vars:v,answer:a,unit:'mg/dose',prompt:`A ${v.kg}-kg child is prescribed ${v.drug} ${v.daily} mg/kg/day divided ${v.freq}. How many mg should be given per dose?`,formula:'mg/kg/day × kg ÷ doses/day = mg/dose',solution:`${v.daily} × ${v.kg} = ${day} mg/day; ${day} ÷ ${v.doses} = ${a} mg/dose`}}
    return current;
  }
  function hidePanels(){answerEl.hidden=true;formulaEl.hidden=true;formulaEl.textContent='';formulaBtn.textContent='Show Formula'}
  function show(q,refreshFields=true){current=q;labelEl.textContent=q.type;problemEl.textContent=q.prompt;answerEl.innerHTML=`<strong>Answer:</strong> ${q.answer}${q.unit?` ${q.unit}`:''}<br><span>${q.solution}</span>`;hidePanels();if(refreshFields)renderFields(q.vars||{})}
  function randomQuestion(){show(E.generate(typeEl.value,difficultyEl.value),true)}
  function applyVars(){show(rebuild(typeEl.value,readVars()),true)}
  typeEl.addEventListener('change',randomQuestion);difficultyEl.addEventListener('change',randomQuestion);document.querySelector('#new-question').addEventListener('click',randomQuestion);document.querySelector('#apply-vars').addEventListener('click',applyVars);document.querySelector('#reveal').addEventListener('click',()=>{answerEl.hidden=!answerEl.hidden});formulaBtn.addEventListener('click',()=>{if(formulaEl.hidden){formulaEl.textContent=current?.formula||'';formulaEl.hidden=false;formulaBtn.textContent='Hide Formula'}else{formulaEl.hidden=true;formulaBtn.textContent='Show Formula'}});
  randomQuestion();
})();