(() => {
  const typeEl=document.querySelector('#type'),difficultyEl=document.querySelector('#difficulty'),varsEl=document.querySelector('#variables'),problemEl=document.querySelector('#problem'),answerEl=document.querySelector('#answer-panel'),labelEl=document.querySelector('#type-label');
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const round=(n,p=1)=>{const f=10**p;return Math.round((Number(n)+Number.EPSILON)*f)/f};
  const n=(label,value,step='any')=>({label,value,type:'number',step});
  const s=(label,value)=>({label,value,type:'text'});
  const diff=()=>difficultyEl.value;
  let current=null;

  const configs={
    'basic-dose':{label:'Basic medication dose',fields:v=>[s('Medication',v.drug),n('Ordered dose (mg)',v.order),n('Available dose (mg)',v.have),n('Available quantity',v.qty),s('Quantity unit',v.unit),s('Route',v.route)],random(){const c=pick(diff()==='easy'?[['acetaminophen',650,325,1,'tablet','PO'],['amoxicillin',500,250,5,'mL','PO']]:diff()==='challenge'?[['amoxicillin',425,250,5,'mL','PO'],['ondansetron',5.5,4,2,'mL','IV']]:[['cephalexin',375,250,5,'mL','PO'],['ondansetron',6,4,2,'mL','IV']]);return{drug:c[0],order:c[1],have:c[2],qty:c[3],unit:c[4],route:c[5]}},build(v){const a=round(v.order/v.have*v.qty,1);return{prompt:`A patient has an order for ${v.drug} ${v.order} mg ${v.route}. Available: ${v.have} mg per ${v.qty} ${v.unit}. How many ${v.unit} should the nurse administer?`,answer:`${a} ${v.unit}`,solution:`(${v.order} ÷ ${v.have}) × ${v.qty} = ${a} ${v.unit}`}}},
    'weight-dose':{label:'Weight-based dose',fields:v=>[s('Medication',v.drug),n('Weight (kg)',v.kg),n('Dose (mg/kg/dose)',v.dose),s('Route/frequency',v.route)],random(){const c=pick(diff()==='challenge'?[['gentamicin',67.3,1.7,'IV q8h'],['vancomycin',61.7,17.5,'IV per dose']]:[['clindamycin',29.4,10,'IV per dose'],['vancomycin',56.8,15,'IV per dose'],['acetaminophen',24.5,15,'PO per dose']]);return{drug:c[0],kg:c[1],dose:c[2],route:c[3]}},build(v){const a=round(v.kg*v.dose,1);return{prompt:`A ${v.kg}-kg patient is prescribed ${v.drug} ${v.dose} mg/kg/dose ${v.route}. How many mg should the patient receive per dose?`,answer:`${a} mg`,solution:`${v.dose} mg/kg × ${v.kg} kg = ${a} mg/dose`}}},
    'peds-safe-range':{label:'Pediatric safe-dose range',fields:v=>[n('Weight (kg)',v.kg),n('Order (mg/dose)',v.order),n('Minimum mg/kg/day',v.minDay),n('Maximum mg/kg/day',v.maxDay),n('Doses per day',v.doses),s('Frequency',v.freq),n('Available mg',v.have),n('Available mL',v.qty)],random(){const c=pick(diff()==='challenge'?[[19.3,118,25,50,4,'q6h',250,5],[27.9,705,25,50,2,'q12h',250,5]]:[[23.4,115,25,50,4,'q6h',125,5],[18.7,275,25,50,2,'q12h',250,5],[31.6,425,25,50,2,'q12h',250,5]]);return{kg:c[0],order:c[1],minDay:c[2],maxDay:c[3],doses:c[4],freq:c[5],have:c[6],qty:c[7]}},build(v){const min=round(v.kg*v.minDay/v.doses,1),max=round(v.kg*v.maxDay/v.doses,1),status=v.order<min?'Too low':v.order>max?'Too high':'Safe',ml=round(v.order*v.qty/v.have,1);return{prompt:`A child weighs ${v.kg} kg. The provider orders cephalexin ${v.order} mg PO ${v.freq}. Recommended: ${v.minDay}–${v.maxDay} mg/kg/day in equally divided doses. Available: ${v.have} mg/${v.qty} mL. Is the ordered dose safe, too low, or too high?`,answer:status,solution:`Safe range: ${min}–${max} mg/dose. Order: ${v.order} mg/dose → ${status}.${status==='Safe'?` Amount to administer: ${ml} mL.`:''}`}}},
    'mlhr-hours':{label:'mL/hr — hours',fields:v=>[n('Volume (mL)',v.volume),n('Time (hours)',v.hours)],random(){return{volume:pick([250,500,1000]),hours:pick(diff()==='challenge'?[1.8,3.75,7.25]:[2.25,4.5,7.5,8])}},build(v){const a=round(v.volume/v.hours,1);return{prompt:`Infuse ${v.volume} mL over ${v.hours} hours. What rate should the IV pump be programmed to?`,answer:`${a} mL/hr`,solution:`${v.volume} ÷ ${v.hours} = ${a} mL/hr`}}},
    'mlhr-minutes':{label:'mL/hr — minutes',fields:v=>[n('Volume (mL)',v.volume),n('Time (minutes)',v.minutes)],random(){return{volume:pick([100,150,250]),minutes:pick(diff()==='challenge'?[37,47,83]:[30,45,55,90,105])}},build(v){const a=round(v.volume/(v.minutes/60),1);return{prompt:`Infuse ${v.volume} mL over ${v.minutes} minutes. What rate should the IV pump be programmed to?`,answer:`${a} mL/hr`,solution:`${v.minutes} min ÷ 60 = ${round(v.minutes/60,2)} hr; ${v.volume} ÷ ${round(v.minutes/60,2)} = ${a} mL/hr`}}},
    'infusion-time':{label:'Infusion duration',fields:v=>[n('Volume (mL)',v.volume),n('Rate (mL/hr)',v.rate)],random(){return{volume:pick([250,500,1000]),rate:pick(diff()==='challenge'?[87,113,117]:[92,100,108,115,125])}},build(v){const a=round(v.volume/v.rate,2);return{prompt:`${v.volume} mL is infusing at ${v.rate} mL/hr. How many hours will the infusion take?`,answer:`${a} hours`,solution:`${v.volume} ÷ ${v.rate} = ${a} hours`}}},
    'completion-time':{label:'Completion time',fields:v=>[s('Start time (24-hour)',v.start),n('Volume (mL)',v.volume),n('Rate (mL/hr)',v.rate)],random(){return{start:pick(['08:15','13:45','21:30','23:17']),volume:pick([250,500,1000]),rate:pick([93,110,115,117,125])}},build(v){const [h,m]=v.start.split(':').map(Number),mins=Math.round(v.volume/v.rate*60),end=(h*60+m+mins)%1440,ans=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;return{prompt:`${v.volume} mL starts at ${v.start} and infuses at ${v.rate} mL/hr. Using 24-hour time, when will it finish?`,answer:ans,solution:`Infusion time ≈ ${mins} minutes. ${v.start} + ${mins} min = ${ans}`}}},
    'gtt-volume-time':{label:'gtt/min — volume + time',fields:v=>[n('Volume (mL)',v.volume),n('Time (hours)',v.hours),n('Drop factor (gtt/mL)',v.drop)],random(){return{volume:pick([250,500,1000]),hours:pick([1.8,2.25,4.75,5.5,7.25,7.5,8]),drop:pick([10,15,20])}},build(v){const a=Math.round(v.volume*v.drop/(v.hours*60));return{prompt:`Infuse ${v.volume} mL over ${v.hours} hours. Drop factor: ${v.drop} gtt/mL. Calculate gtt/min.`,answer:`${a} gtt/min`,solution:`(${v.volume} × ${v.drop}) ÷ (${v.hours} × 60) = ${a} gtt/min`}}},
    'gtt-from-mlhr':{label:'mL/hr → gtt/min',fields:v=>[n('Rate (mL/hr)',v.rate),n('Drop factor (gtt/mL)',v.drop)],random(){return{rate:pick([83,100,108,113,117,125,127]),drop:pick([10,15,20])}},build(v){const a=Math.round(v.rate*v.drop/60);return{prompt:`An IV runs at ${v.rate} mL/hr using tubing ${v.drop} gtt/mL. What gravity rate should be set?`,answer:`${a} gtt/min`,solution:`(${v.rate} × ${v.drop}) ÷ 60 = ${a} gtt/min`}}},
    'mlhr-from-gtt':{label:'gtt/min → mL/hr',fields:v=>[n('Flow (gtt/min)',v.gtt),n('Drop factor (gtt/mL)',v.drop)],random(){return{gtt:pick([19,25,27,31,40,43,47]),drop:pick([10,15,20])}},build(v){const a=round(v.gtt*60/v.drop,1);return{prompt:`An IV is running at ${v.gtt} gtt/min using tubing ${v.drop} gtt/mL. What is the equivalent mL/hr rate?`,answer:`${a} mL/hr`,solution:`(${v.gtt} × 60) ÷ ${v.drop} = ${a} mL/hr`}}},
    'reconstitution':{label:'Reconstitution',fields:v=>[s('Medication',v.drug),n('Ordered dose (mg)',v.order),n('Final concentration (mg/mL)',v.conc)],random(){const c=pick([['cefazolin',825,330],['methylprednisolone',75,62.5],['ampicillin',500,250]]);return{drug:c[0],order:c[1],conc:c[2]}},build(v){const a=round(v.order/v.conc,2);return{prompt:`After reconstitution, ${v.drug} is labeled ${v.conc} mg/mL. The order is ${v.order} mg. How many mL should the nurse draw up?`,answer:`${a} mL`,solution:`${v.order} ÷ ${v.conc} = ${a} mL`}}},
    'units-hour':{label:'Units/hr infusion',fields:v=>[s('Medication',v.drug),n('Ordered units/hr',v.order),n('Bag total units',v.total),n('Bag volume (mL)',v.ml)],random(){return{drug:'heparin',order:pick([1175,1200,1375]),total:25000,ml:500}},build(v){const a=round(v.order*v.ml/v.total,1);return{prompt:`${v.drug} is ordered at ${v.order} units/hr. Bag: ${v.total} units in ${v.ml} mL. Set the pump to how many mL/hr?`,answer:`${a} mL/hr`,solution:`${v.order} × ${v.ml} ÷ ${v.total} = ${a} mL/hr`}}},
    'mcg-minute':{label:'mcg/min infusion',fields:v=>[s('Medication',v.drug),n('Ordered mcg/min',v.order),n('Bag total mcg',v.total),n('Bag volume (mL)',v.ml)],random(){return{drug:'nitroglycerin',order:pick([20,37,43]),total:50000,ml:250}},build(v){const a=round(v.order*60*v.ml/v.total,1);return{prompt:`${v.drug} is ordered at ${v.order} mcg/min. Bag: ${v.total} mcg in ${v.ml} mL. Set the pump to how many mL/hr?`,answer:`${a} mL/hr`,solution:`${v.order} × 60 × ${v.ml} ÷ ${v.total} = ${a} mL/hr`}}},
    'mcg-kg-minute':{label:'mcg/kg/min infusion',fields:v=>[s('Medication',v.drug),n('Weight (kg)',v.kg),n('Dose (mcg/kg/min)',v.dose),n('Bag total mcg',v.total),n('Bag volume (mL)',v.ml)],random(){return{drug:pick(['dopamine','dobutamine','norepinephrine']),kg:pick([60,67.3,70,80]),dose:pick([.08,5,6.5,7.5]),total:pick([8000,250000,400000]),ml:250}},build(v){const a=round(v.dose*v.kg*60*v.ml/v.total,1);return{prompt:`${v.drug} ${v.dose} mcg/kg/min is ordered for a ${v.kg}-kg patient. Bag: ${v.total} mcg in ${v.ml} mL. Set the pump to how many mL/hr?`,answer:`${a} mL/hr`,solution:`${v.dose} × ${v.kg} × 60 × ${v.ml} ÷ ${v.total} = ${a} mL/hr`}}},
    'amount-hour':{label:'mg/hr or g/hr infusion',fields:v=>[s('Medication',v.drug),n('Ordered amount/hr',v.order),s('Mass unit',v.unit),n('Bag total amount',v.total),n('Bag volume (mL)',v.ml)],random(){const c=pick([['amiodarone',60,'mg',450,250],['magnesium sulfate',2,'g',20,500],['calcium gluconate',1,'g',10,500]]);return{drug:c[0],order:c[1],unit:c[2],total:c[3],ml:c[4]}},build(v){const a=round(v.order*v.ml/v.total,1);return{prompt:`${v.drug} is ordered at ${v.order} ${v.unit}/hr. Bag: ${v.total} ${v.unit} in ${v.ml} mL. Set the pump to how many mL/hr?`,answer:`${a} mL/hr`,solution:`${v.order} × ${v.ml} ÷ ${v.total} = ${a} mL/hr`}}},
    'meq-ml':{label:'mEq to mL',fields:v=>[s('Medication',v.drug),n('Ordered mEq',v.order),n('Concentration (mEq/mL)',v.conc)],random(){return{drug:pick(['potassium chloride','sodium bicarbonate','potassium acetate']),order:pick([17,20,25,30,37]),conc:pick([1,2])}},build(v){const a=round(v.order/v.conc,1);return{prompt:`${v.drug} order: ${v.order} mEq. Available: ${v.conc} mEq/mL. How many mL should be administered?`,answer:`${a} mL`,solution:`${v.order} ÷ ${v.conc} = ${a} mL`}}},
    'daily-divided':{label:'Daily divided dose',fields:v=>[s('Medication',v.drug),n('Weight (kg)',v.kg),n('Daily dose (mg/kg/day)',v.daily),n('Doses per day',v.doses)],random(){return{drug:pick(['amoxicillin','cephalexin','clindamycin']),kg:pick([18.7,23.4,31.6]),daily:pick([25,30,40,50]),doses:pick([2,3,4])}},build(v){const day=round(v.kg*v.daily,1),a=round(day/v.doses,1);return{prompt:`A ${v.kg}-kg child is prescribed ${v.drug} ${v.daily} mg/kg/day divided into ${v.doses} equal doses. How many mg should the child receive per dose?`,answer:`${a} mg/dose`,solution:`${v.kg} × ${v.daily} = ${day} mg/day; ${day} ÷ ${v.doses} = ${a} mg/dose`}}}
  };

  Object.entries(configs).forEach(([key,c])=>typeEl.add(new Option(c.label,key)));

  function renderFields(v){
    const cfg=configs[typeEl.value];
    varsEl.innerHTML='';
    cfg.fields(v).forEach((f,idx)=>{
      const label=document.createElement('label');label.textContent=f.label;
      const input=document.createElement('input');input.dataset.idx=idx;input.type=f.type;input.value=f.value; if(f.step)input.step=f.step;
      label.appendChild(input);varsEl.appendChild(label);
    });
  }
  function readVars(){const cfg=configs[typeEl.value],base={...current.vars};cfg.fields(base).forEach((f,idx)=>{const input=varsEl.querySelector(`[data-idx="${idx}"]`);const key=Object.keys(base)[idx];if(key)base[key]=f.type==='number'?Number(input.value):input.value});return base}
  function show(q){current=q;labelEl.textContent=configs[typeEl.value].label;problemEl.textContent=q.prompt;answerEl.hidden=true;answerEl.innerHTML=`<strong>Answer:</strong> ${q.answer}<br><span>${q.solution}</span>`}
  function randomQuestion(){const cfg=configs[typeEl.value],vars=cfg.random();renderFields(vars);show({...cfg.build(vars),vars})}
  function applyVars(){const cfg=configs[typeEl.value],vars=readVars();renderFields(vars);show({...cfg.build(vars),vars})}
  typeEl.addEventListener('change',randomQuestion);difficultyEl.addEventListener('change',randomQuestion);
  document.querySelector('#new-question').addEventListener('click',randomQuestion);
  document.querySelector('#apply-vars').addEventListener('click',applyVars);
  document.querySelector('#reveal').addEventListener('click',()=>{answerEl.hidden=!answerEl.hidden});
  randomQuestion();
})();
