(() => {
  const E=window.DosageEngine;if(!E)throw new Error('DosageEngine not loaded');
  const shuffle=a=>{a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a};
  const typeList=document.querySelector('#type-list'),titleInput=document.querySelector('#quiz-title'),review=document.querySelector('#review'),questionList=document.querySelector('#question-list'),status=document.querySelector('#status'),publishStatus=document.querySelector('#publish-status'),approved=document.querySelector('#approved'),publish=document.querySelector('#publish');
  let draft=null;
  const families=E.families||[{key:'all',label:'All Question Types',description:'All available calculations.',types:E.types.map(t=>t.key)}];
  const typeLabel=k=>E.typeLabel?E.typeLabel(k):(E.types.find(t=>t.key===k)?.label||k);
  typeList.innerHTML=families.map((f,idx)=>`<section class="type-family"><label><input type="checkbox" name="family" value="${f.key}" ${idx===0?'checked':''}> <strong>${f.label}</strong></label><p class="status">${f.description||''}</p><label class="field">Focus<select data-family-select="${f.key}"><option value="all">All ${f.label}</option>${f.types.map(k=>`<option value="${k}">${typeLabel(k)}</option>`).join('')}</select></label></section>`).join('');
  const selectedPlan=()=>{const familiesChosen=[],keys=[];document.querySelectorAll('input[name="family"]:checked').forEach(cb=>{const f=families.find(x=>x.key===cb.value);if(!f)return;const focus=document.querySelector(`[data-family-select="${f.key}"]`)?.value||'all';familiesChosen.push({family:f.key,focus});if(focus==='all')keys.push(...f.types);else keys.push(focus)});return{families:familiesChosen,keys:[...new Set(keys)]}};
  const difficulty=()=>document.querySelector('input[name="difficulty"]:checked')?.value||'standard';
  const questionCount=()=>+(document.querySelector('input[name="count"]:checked')?.value||20);
  const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||`quiz-${Date.now()}`;
  const fingerprint=x=>E.semanticSignature?E.semanticSignature(x):`${x.key}|${String(x.prompt).toLowerCase().replace(/\s+/g,' ').trim()}`;
  function unique(key,used,max=1200){for(let n=0;n<max;n++){const x=E.generate(key,difficulty());if(!used.has(fingerprint(x)))return x}return null}
  function resetApproval(message='Draft changed. Review approval reset.'){approved.checked=false;publish.disabled=true;publishStatus.textContent=message}
  function buildDraft(){const plan=selectedPlan(),keys=plan.keys;if(!keys.length){status.textContent='Choose at least one question family.';return}const ordered=shuffle(keys),used=new Set(),questions=[];try{for(let n=0;n<questionCount();n++){let key=ordered[n%ordered.length],x=unique(key,used);if(!x){for(const alt of shuffle(ordered)){x=unique(alt,used,160);if(x){key=alt;break}}}if(!x)throw new Error('Could not create another meaningfully different question from the selected family mix.');used.add(fingerprint(x));questions.push(x)}}catch(err){status.textContent=`${err.message} Lower the question count, broaden the family selection, or choose a different difficulty.`;return}const title=titleInput.value.trim()||'Instructor Quiz';draft={version:6,engineVersion:E.version,id:slug(title),title,status:'draft',difficulty:difficulty(),createdAt:new Date().toISOString(),questionCount:questions.length,selectedFamilies:plan.families,questionTypes:[...new Set(questions.map(x=>x.key))],questions};approved.checked=false;publish.disabled=true;publishStatus.textContent='';status.textContent=`Draft created with ${questions.length} frozen ${difficulty()} questions. Broad families are balanced across their available subtypes; clinically equivalent variants are blocked.`;renderReview()}
  function renderReview(){review.hidden=false;document.querySelector('#review-title').textContent=draft.title;questionList.innerHTML=draft.questions.map((x,idx)=>`<article class="question-row"><div class="qnum">${idx+1}</div><div><p>${x.prompt}</p><div class="answer">${x.answer}${x.unit?` ${x.unit}`:''}<span class="badge">${x.type}</span></div><details><summary>Formula & solution</summary><p><strong>${x.formula}</strong></p><p>${String(x.solution).replace(/\n/g,'<br>')}</p></details></div><button class="secondary replace" data-random="${idx}">Replace</button></article>`).join('')}
  function randomizeOne(index){const used=new Set(draft.questions.filter((_,i)=>i!==index).map(fingerprint)),replacement=unique(draft.questions[index].key,used);if(!replacement){publishStatus.textContent='No additional meaningfully different question is available for that subtype at this difficulty.';return}draft.questions[index]=replacement;draft.questionTypes=[...new Set(draft.questions.map(x=>x.key))];resetApproval('Question replaced with a different clinical/math variant. Review approval reset.');renderReview()}
  async function publishDraft(){if(!draft||!approved.checked)return;draft.status='published';draft.publishedAt=new Date().toISOString();publish.disabled=true;publishStatus.textContent='Publishing…';try{const res=await fetch('/instructor-api/instructor-quizzes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();publishStatus.textContent=`Published. Students can now open “${draft.title}”.`;if(data.id)draft.id=data.id}catch(err){draft.status='approved';const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${draft.id}.json`;a.click();URL.revokeObjectURL(url);publishStatus.textContent='Secure publish endpoint is not available, so the approved quiz JSON was downloaded instead.';publish.disabled=false}}
  typeList.addEventListener('change',e=>{const s=e.target.closest('[data-family-select]');if(s&&s.value!=='all'){const cb=typeList.querySelector(`input[name="family"][value="${s.dataset.familySelect}"]`);if(cb)cb.checked=true}});
  document.querySelector('#generate').addEventListener('click',buildDraft);document.querySelector('#regenerate').addEventListener('click',buildDraft);document.querySelector('#clear').addEventListener('click',()=>{draft=null;review.hidden=true;status.textContent='';publishStatus.textContent=''});questionList.addEventListener('click',e=>{const b=e.target.closest('[data-random]');if(b)randomizeOne(+b.dataset.random)});approved.addEventListener('change',()=>publish.disabled=!approved.checked);publish.addEventListener('click',publishDraft);
})();