(() => {
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const shuffle=a=>{a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a};
  const round=(n,p=1)=>{const f=10**p;return Math.round((n+Number.EPSILON)*f)/f};
  const q=(key,type,prompt,answer,unit,formula,note,solution,tolerance=.05,vars={})=>({key,type,prompt,answer,unit,formula,note,solution,tolerance,vars});
  const difficulty=()=>document.querySelector('input[name="difficulty"]:checked')?.value||'standard';
  const byDifficulty=(easy,standard,challenge)=>difficulty()==='easy'?easy:difficulty()==='challenge'?challenge:standard;

  function basicDose(){const c=pick(byDifficulty(
    [{drug:'acetaminophen',order:650,have:325,qty:1,unit:'tablets',route:'PO'}],
    [{drug:'cephalexin',order:375,have:250,qty:5,unit:'mL',route:'PO'},{drug:'ondansetron',order:6,have:4,qty:2,unit:'mL',route:'IV'}],
    [{drug:'amoxicillin',order:425,have:250,qty:5,unit:'mL',route:'PO'},{drug:'prednisone',order:27.5,have:10,qty:1,unit:'tablets',route:'PO'}]));
    const a=round(c.order/c.have*c.qty,1);return q('basic-dose','Basic medication dose',`A patient has an order for ${c.drug} ${c.order} mg ${c.route}. Available: ${c.have} mg per ${c.qty} ${c.unit}. How many ${c.unit} should the nurse administer?`,a,c.unit,'Desired ÷ Have × Quantity = amount to give','Match the ordered dose to the concentration on hand.',`(${c.order} ÷ ${c.have}) × ${c.qty} = ${a} ${c.unit}`,.06,c)}

  function weightDose(){const c=pick(byDifficulty(
    [{drug:'gentamicin',kg:70.5,dose:1.5,route:'IV q8h'}],
    [{drug:'clindamycin',kg:29.4,dose:10,route:'IV per dose'},{drug:'vancomycin',kg:56.8,dose:15,route:'IV per dose'}],
    [{drug:'gentamicin',kg:67.3,dose:1.7,route:'IV q8h'},{drug:'vancomycin',kg:61.7,dose:17.5,route:'IV per dose'}]));const a=round(c.kg*c.dose,1);return q('weight-dose','Weight-based dose',`A ${c.kg}-kg patient is prescribed ${c.drug} ${c.dose} mg/kg/dose ${c.route}. How many mg should the patient receive per dose?`,a,'mg','mg/kg/dose × kg = mg per dose','Multiply dose per kilogram by weight.',`${c.dose} × ${c.kg} = ${a} mg/dose`,.06,c)}

  function pedsSafe(){const c=pick(byDifficulty(
    [{kg:18.5,order:300,freq:'q12h',doses:2,have:250,qty:5}],
    [{kg:23.4,order:115,freq:'q6h',doses:4,have:125,qty:5},{kg:18.7,order:275,freq:'q12h',doses:2,have:250,qty:5}],
    [{kg:19.3,order:118,freq:'q6h',doses:4,have:250,qty:5},{kg:27.9,order:705,freq:'q12h',doses:2,have:250,qty:5}]));
    const min=round(c.kg*25/c.doses,1),max=round(c.kg*50/c.doses,1),safety=c.order<min?'too low':c.order>max?'too high':'safe',ml=round(c.order*c.qty/c.have,1);
    return q('peds-safe-range','Pediatric safe-dose range',`A child weighs ${c.kg} kg. The provider orders cephalexin ${c.order} mg PO ${c.freq}. Recommended: 25–50 mg/kg/day in equally divided doses. Available: ${c.have} mg/${c.qty} mL. Is the ordered dose safe, too low, or too high?`,safety,'','mg/kg/day × kg ÷ doses/day = safe mg/dose range','Find the min/max per-dose range before comparing the order.',`Safe range: ${min}–${max} mg/dose. Order ${c.order} mg is ${safety}.${safety==='safe'?` Amount: ${ml} mL.`:''}`,.05,{...c,min,max,ml})}

  function mlhr(){const[v,h]=pick(byDifficulty([[1000,8],[500,4]],[[1000,7.5],[500,4.5],[250,2.25]],[[1000,7.25],[500,3.75],[250,1.8]]));const a=round(v/h,1);return q('mlhr-hours','mL/hr — hours',`Infuse ${v} mL over ${h} hours. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ hours = mL/hr','Divide volume by hours.',`${v} ÷ ${h} = ${a} mL/hr`,.05,{volume:v,hours:h})}
  function mlhrMin(){const[v,m]=pick(byDifficulty([[100,30],[250,90]],[[100,45],[250,105],[150,55]],[[100,37],[250,83],[150,47]]));const a=round(v/(m/60),1);return q('mlhr-minutes','mL/hr — minutes',`Infuse ${v} mL over ${m} minutes. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ (minutes ÷ 60) = mL/hr','Convert minutes to hours first.',`${v} ÷ (${m} ÷ 60) = ${a} mL/hr`,.05,{volume:v,minutes:m})}
  function duration(){const[v,r]=pick(byDifficulty([[1000,125],[500,100]],[[1000,115],[500,92],[250,108]],[[1000,117],[500,87],[250,113]]));const a=round(v/r,2);return q('infusion-time','Infusion duration',`${v} mL is infusing at ${r} mL/hr. How many hours will the infusion take?`,a,'hours','mL ÷ mL/hr = hours','Divide volume by rate.',`${v} ÷ ${r} = ${a} hr`,.02,{volume:v,rate:r})}
  function completion(){const c=pick(byDifficulty([{start:'08:15',v:1000,r:125}],[{start:'21:30',v:500,r:110},{start:'13:45',v:250,r:115}],[{start:'23:17',v:500,r:93},{start:'06:23',v:1000,r:117}]));const[hh,mm]=c.start.split(':').map(Number),mins=Math.round(c.v/c.r*60),end=(hh*60+mm+mins)%1440,ans=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;return q('completion-time','Completion time',`${c.v} mL starts at ${c.start} and infuses at ${c.r} mL/hr. Using 24-hour time, when will it finish?`,ans,'','start time + infusion duration = finish time','Find the duration, then add it to the start time.',`${c.v} ÷ ${c.r} hr; finish = ${ans}`,0,c)}
  function gtt(){const[v,h,d]=pick(byDifficulty([[1000,8,15],[500,4,20]],[[1000,7.5,15],[500,5.5,20],[250,2.25,10]],[[1000,7.25,15],[500,4.75,20],[250,1.8,10]]));const a=Math.round(v*d/(h*60));return q('gtt-volume-time','gtt/min — volume + time',`Infuse ${v} mL over ${h} hours. Drop factor: ${d} gtt/mL. Calculate gtt/min.`,a,'gtt/min','(mL × gtt/mL) ÷ minutes = gtt/min','Convert hours to minutes and round to a whole drop.',`(${v} × ${d}) ÷ ${h*60} = ${a} gtt/min`,.05,{volume:v,hours:h,dropFactor:d})}
  function gttFromMlhr(){const[r,d]=pick(byDifficulty([[100,15],[125,20]],[[108,15],[117,20],[83,10]],[[113,15],[127,20],[89,10]]));const a=Math.round(r*d/60);return q('gtt-from-mlhr','mL/hr → gtt/min',`An IV runs at ${r} mL/hr using tubing ${d} gtt/mL. What is the gravity rate?`,a,'gtt/min','(mL/hr × gtt/mL) ÷ 60 = gtt/min','Convert hourly rate to drops per minute.',`(${r} × ${d}) ÷ 60 = ${a} gtt/min`,.05,{rate:r,dropFactor:d})}
  function mlhrFromGtt(){const[g,d]=pick(byDifficulty([[25,15],[40,20]],[[27,15],[43,20],[19,10]],[[31,15],[47,20],[23,10]]));const a=round(g*60/d,1);return q('mlhr-from-gtt','gtt/min → mL/hr',`${g} gtt/min is running through tubing ${d} gtt/mL. What is the mL/hr rate?`,a,'mL/hr','(gtt/min × 60) ÷ gtt/mL = mL/hr','Convert drops/min to drops/hour, then divide by drop factor.',`(${g} × 60) ÷ ${d} = ${a} mL/hr`,.05,{dropsPerMinute:g,dropFactor:d})}

  function reconstitution(){const c=pick(byDifficulty([{drug:'ampicillin',order:500,conc:250}],[{drug:'cefazolin',order:825,conc:330},{drug:'methylprednisolone',order:75,conc:62.5}],[{drug:'cefazolin',order:775,conc:330},{drug:'methylprednisolone',order:87.5,conc:62.5}]));const a=round(c.order/c.conc,2);return q('reconstitution','Reconstitution',`After reconstitution, ${c.drug} is ${c.conc} mg/mL. Order: ${c.order} mg. How many mL?`,a,'mL','ordered dose ÷ concentration = mL','Use the final concentration.',`${c.order} ÷ ${c.conc} = ${a} mL`,.03,c)}
  function unitsHr(){const c=pick(byDifficulty([{drug:'heparin',order:1200,bagUnits:25000,bagMl:500}],[{drug:'heparin',order:1175,bagUnits:25000,bagMl:500},{drug:'regular insulin',order:6,bagUnits:100,bagMl:100}],[{drug:'heparin',order:1375,bagUnits:25000,bagMl:500},{drug:'regular insulin',order:7.5,bagUnits:100,bagMl:100}]));const a=round(c.order*c.bagMl/c.bagUnits,1);return q('units-hour','Units/hr infusion',`${c.drug} is ordered at ${c.order} units/hr. Bag: ${c.bagUnits.toLocaleString()} units in ${c.bagMl} mL. Set the pump to?`,a,'mL/hr','units/hr × mL ÷ total units = mL/hr','Use the concentration in the bag.',`${c.order} × ${c.bagMl} ÷ ${c.bagUnits} = ${a} mL/hr`,.05,c)}
  function mcgMin(){const c=pick(byDifficulty([{drug:'nitroglycerin',order:20,bagMcg:50000,bagMl:250}],[{drug:'nitroglycerin',order:37,bagMcg:50000,bagMl:250},{drug:'dopamine',order:400,bagMcg:400000,bagMl:250}],[{drug:'nitroglycerin',order:43,bagMcg:50000,bagMl:250},{drug:'dobutamine',order:275,bagMcg:250000,bagMl:250}]));const a=round(c.order*60*c.bagMl/c.bagMcg,1);return q('mcg-minute','mcg/min infusion',`${c.drug} is ordered at ${c.order} mcg/min. Bag: ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. Set mL/hr.`,a,'mL/hr','mcg/min × 60 × mL ÷ total mcg = mL/hr','Convert minute dose to hourly dose first.',`${c.order} × 60 × ${c.bagMl} ÷ ${c.bagMcg} = ${a} mL/hr`,.05,c)}
  function mcgKgMin(){const c=pick(byDifficulty([{drug:'dopamine',kg:70,dose:5,bagMcg:400000,bagMl:250}],[{drug:'norepinephrine',kg:80,dose:.08,bagMcg:8000,bagMl:250},{drug:'dobutamine',kg:60,dose:7.5,bagMcg:250000,bagMl:250}],[{drug:'epinephrine',kg:75,dose:.05,bagMcg:4000,bagMl:250},{drug:'dopamine',kg:67.3,dose:6.5,bagMcg:400000,bagMl:250}]));const a=round(c.dose*c.kg*60*c.bagMl/c.bagMcg,1);return q('mcg-kg-minute','mcg/kg/min infusion',`${c.drug} ${c.dose} mcg/kg/min for a ${c.kg}-kg patient. Bag: ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. Set mL/hr.`,a,'mL/hr','mcg/kg/min × kg × 60 × mL ÷ mcg = mL/hr','Calculate mcg/min first, then hourly pump rate.',`${c.dose} × ${c.kg} × 60 × ${c.bagMl} ÷ ${c.bagMcg} = ${a} mL/hr`,.05,c)}
  function amountHr(){const c=pick(byDifficulty([{drug:'magnesium sulfate',order:2,unit:'g',bagAmt:20,bagMl:500}],[{drug:'amiodarone',order:60,unit:'mg',bagAmt:450,bagMl:250},{drug:'calcium gluconate',order:1,unit:'g',bagAmt:10,bagMl:500}],[{drug:'amiodarone',order:67.5,unit:'mg',bagAmt:450,bagMl:250},{drug:'magnesium sulfate',order:1.7,unit:'g',bagAmt:20,bagMl:500}]));const a=round(c.order*c.bagMl/c.bagAmt,1);return q('amount-hour','mg/hr or g/hr infusion',`${c.drug} is ordered at ${c.order} ${c.unit}/hr. Bag: ${c.bagAmt} ${c.unit} in ${c.bagMl} mL. Set mL/hr.`,a,'mL/hr',`${c.unit}/hr × mL ÷ total ${c.unit} = mL/hr`,'Keep the same mass unit in numerator and denominator.',`${c.order} × ${c.bagMl} ÷ ${c.bagAmt} = ${a} mL/hr`,.05,c)}
  function meqMl(){const c=pick(byDifficulty([{drug:'potassium chloride',order:20,conc:2}],[{drug:'potassium chloride',order:30,conc:2},{drug:'sodium bicarbonate',order:25,conc:1}],[{drug:'potassium acetate',order:17,conc:2},{drug:'sodium bicarbonate',order:37,conc:1}]));const a=round(c.order/c.conc,1);return q('meq-ml','mEq to mL',`${c.drug} order: ${c.order} mEq. Available: ${c.conc} mEq/mL. How many mL?`,a,'mL','mEq ÷ mEq/mL = mL','Divide ordered mEq by concentration.',`${c.order} ÷ ${c.conc} = ${a} mL`,.05,c)}
  function dailyDivided(){const c=pick(byDifficulty([{drug:'amoxicillin',kg:18,dose:40,doses:2,freq:'q12h'}],[{drug:'cephalexin',kg:24.3,dose:50,doses:4,freq:'q6h'},{drug:'clindamycin',kg:30.4,dose:30,doses:3,freq:'q8h'}],[{drug:'cefuroxime',kg:20.7,dose:30,doses:2,freq:'q12h'},{drug:'acetaminophen',kg:16.8,dose:60,doses:4,freq:'q6h'}]));const a=round(c.kg*c.dose/c.doses,1);return q('daily-divided','Daily divided dose',`${c.drug} is ordered at ${c.dose} mg/kg/day for a ${c.kg}-kg patient, divided ${c.freq}. How many mg per dose?`,a,'mg/dose','mg/kg/day × kg ÷ doses/day = mg/dose','Calculate the full daily amount before dividing.',`${c.dose} × ${c.kg} ÷ ${c.doses} = ${a} mg/dose`,.05,c)}

  const defs=[
    ['basic-dose','Basic medication dose',basicDose],['weight-dose','Weight-based dose',weightDose],['peds-safe-range','Pediatric safe-dose range',pedsSafe],
    ['mlhr-hours','mL/hr — hours',mlhr],['mlhr-minutes','mL/hr — minutes',mlhrMin],['infusion-time','Infusion duration',duration],['completion-time','Completion time',completion],
    ['gtt-volume-time','gtt/min — volume + time',gtt],['gtt-from-mlhr','mL/hr → gtt/min',gttFromMlhr],['mlhr-from-gtt','gtt/min → mL/hr',mlhrFromGtt],
    ['reconstitution','Reconstitution',reconstitution],['units-hour','Units/hr infusion',unitsHr],['mcg-minute','mcg/min infusion',mcgMin],['mcg-kg-minute','mcg/kg/min infusion',mcgKgMin],['amount-hour','mg/hr or g/hr infusion',amountHr],['meq-ml','mEq to mL',meqMl],['daily-divided','Daily divided dose',dailyDivided]
  ].map(([key,label,random])=>({key,label,random}));
  const byKey=Object.fromEntries(defs.map(d=>[d.key,d]));

  const typeList=document.querySelector('#type-list'),titleInput=document.querySelector('#quiz-title'),review=document.querySelector('#review'),questionList=document.querySelector('#question-list'),status=document.querySelector('#status'),publishStatus=document.querySelector('#publish-status'),approved=document.querySelector('#approved'),publish=document.querySelector('#publish');
  let draft=null;
  typeList.innerHTML=defs.map((t,i)=>`<label><input type="checkbox" name="type" value="${t.key}" ${i===0?'checked':''}> ${t.label}</label>`).join('');
  const selectedTypes=()=>[...document.querySelectorAll('input[name="type"]:checked')].map(x=>x.value);
  const questionCount=()=>+(document.querySelector('input[name="count"]:checked')?.value||20);
  const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||`quiz-${Date.now()}`;
  function buildQuestion(keys,index){const available=defs.filter(t=>keys.includes(t.key));return available[index%available.length].random()}
  function resetApproval(message='Draft changed. Review approval reset.'){approved.checked=false;publish.disabled=true;publishStatus.textContent=message}
  function buildDraft(){const keys=selectedTypes();if(!keys.length){status.textContent='Choose at least one question type.';return}const count=questionCount(),ordered=shuffle(keys),questions=[];for(let n=0;n<count;n++)questions.push(buildQuestion(ordered,n));const title=titleInput.value.trim()||'Instructor Quiz';draft={version:2,id:slug(title),title,status:'draft',difficulty:difficulty(),createdAt:new Date().toISOString(),questionCount:questions.length,questionTypes:[...new Set(keys)],questions};approved.checked=false;publish.disabled=true;publishStatus.textContent='';status.textContent=`Draft created with ${questions.length} frozen ${difficulty()} questions.`;renderReview()}
  function renderReview(){if(!draft)return;review.hidden=false;document.querySelector('#review-title').textContent=draft.title;questionList.innerHTML=draft.questions.map((x,idx)=>`<article class="question-row"><div class="qnum">${idx+1}</div><div><p>${x.prompt}</p><div class="answer">${x.answer}${x.unit?` ${x.unit}`:''}<span class="badge">${x.type}</span></div><details><summary>Solution</summary><p>${String(x.solution).replace(/\n/g,'<br>')}</p></details></div><button class="secondary replace" data-random="${idx}">Replace</button></article>`).join('')}
  function randomizeOne(index){const def=byKey[draft.questions[index].key];draft.questions[index]=def.random();resetApproval('Question replaced. Review approval reset.');renderReview()}
  async function publishDraft(){if(!draft||!approved.checked)return;draft.status='published';draft.publishedAt=new Date().toISOString();publish.disabled=true;publishStatus.textContent='Publishing…';try{const res=await fetch('/instructor-api/instructor-quizzes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();publishStatus.textContent=`Published. Students can now open “${draft.title}”.`;if(data.id)draft.id=data.id}catch(err){draft.status='approved';const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${draft.id}.json`;a.click();URL.revokeObjectURL(url);publishStatus.textContent='Secure publish endpoint is not available yet, so the approved quiz JSON was downloaded instead.';publish.disabled=false}}
  document.querySelector('#generate').addEventListener('click',buildDraft);
  document.querySelector('#regenerate').addEventListener('click',buildDraft);
  document.querySelector('#clear').addEventListener('click',()=>{draft=null;review.hidden=true;status.textContent='';publishStatus.textContent=''});
  questionList.addEventListener('click',e=>{const b=e.target.closest('[data-random]');if(b)randomizeOne(+b.dataset.random)});
  approved.addEventListener('change',()=>{publish.disabled=!approved.checked});
  publish.addEventListener('click',publishDraft);
})();