(() => {
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const shuffle=a=>{a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a};
  const round=(n,p=1)=>{const f=10**p;return Math.round((n+Number.EPSILON)*f)/f};
  const q=(key,type,prompt,answer,unit,formula,note,solution,tolerance,vars)=>({key,type,prompt,answer,unit,formula,note,solution,tolerance,vars});

  function makeMlhr({volume,hours}){const a=round(volume/hours,1);return q('mlhr-hours','mL/hr',`Infuse ${volume.toLocaleString()} mL over ${hours} ${hours===1?'hour':'hours'}. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ hours = mL/hr','Divide total volume by infusion time.',`${volume.toLocaleString()} mL ÷ ${hours} hr = ${a} mL/hr`,.05,{volume,hours})}
  function makeMlhrMin({volume,minutes}){const h=minutes/60,a=round(volume/h,1);return q('mlhr-minutes','Minutes → mL/hr',`Infuse ${volume} mL over ${minutes} minutes. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ (minutes ÷ 60) = mL/hr','Convert minutes to hours first.',`${minutes} min ÷ 60 = ${round(h,2)} hr\n${volume} mL ÷ ${round(h,2)} hr = ${a} mL/hr`,.05,{volume,minutes})}
  function makeGtt({volume,hours,dropFactor}){const m=hours*60,r=volume*dropFactor/m,a=Math.round(r);return q('gtt-volume-time','gtt/min',`Infuse ${volume.toLocaleString()} mL over ${hours} hours. Tubing drop factor is ${dropFactor} gtt/mL. Calculate the flow rate.`,a,'gtt/min','(mL × gtt/mL) ÷ minutes = gtt/min','Convert hours to minutes; round final answer to a whole drop.',`${hours} hr × 60 = ${m} min\n(${volume} × ${dropFactor}) ÷ ${m} = ${round(r,2)}\nRound = ${a} gtt/min`,.05,{volume,hours,dropFactor})}
  function makeGttFromMlhr({rate,dropFactor}){const x=rate*dropFactor/60,a=Math.round(x);return q('gtt-from-mlhr','mL/hr → gtt/min',`An IV is infusing at ${rate} mL/hr with tubing ${dropFactor} gtt/mL. What gravity flow rate should be set?`,a,'gtt/min','(mL/hr × gtt/mL) ÷ 60 = gtt/min','Convert the hourly rate to drops per minute.',`(${rate} × ${dropFactor}) ÷ 60 = ${round(x,2)}\nRound = ${a} gtt/min`,.05,{rate,dropFactor})}
  function makeMlhrFromGtt({dropsPerMinute,dropFactor}){const a=round(dropsPerMinute*60/dropFactor,1);return q('mlhr-from-gtt','gtt/min → mL/hr',`An IV is running at ${dropsPerMinute} gtt/min using tubing ${dropFactor} gtt/mL. What is the equivalent infusion rate?`,a,'mL/hr','(gtt/min × 60) ÷ gtt/mL = mL/hr','Convert drops per minute to drops per hour, then divide by the drop factor.',`(${dropsPerMinute} × 60) ÷ ${dropFactor} = ${a} mL/hr`,.05,{dropsPerMinute,dropFactor})}
  function makeDuration({volume,rate}){const a=round(volume/rate,2);return q('infusion-time','Infusion duration',`${volume.toLocaleString()} mL is infusing at ${rate} mL/hr. How many hours will the infusion take?`,a,'hours','mL ÷ mL/hr = hours','Divide volume by hourly rate.',`${volume.toLocaleString()} mL ÷ ${rate} mL/hr = ${a} hours`,.02,{volume,rate})}

  const defs=[
    {key:'mlhr-hours',label:'mL/hr — hours',fields:[['volume','Volume (mL)'],['hours','Time (hours)']],make:makeMlhr,random:()=>{const[volume,hours]=pick([[1000,8],[1000,10],[500,4],[500,5],[250,2],[150,1.5],[100,.5],[250,2.5],[1000,12],[500,8]]);return makeMlhr({volume,hours})}},
    {key:'mlhr-minutes',label:'mL/hr — minutes',fields:[['volume','Volume (mL)'],['minutes','Time (minutes)']],make:makeMlhrMin,random:()=>{const[volume,minutes]=pick([[100,30],[250,90],[500,150],[150,45],[50,30],[100,45],[250,120],[75,30]]);return makeMlhrMin({volume,minutes})}},
    {key:'gtt-volume-time',label:'gtt/min — volume + time',fields:[['volume','Volume (mL)'],['hours','Time (hours)'],['dropFactor','Drop factor (gtt/mL)']],make:makeGtt,random:()=>{const[volume,hours,dropFactor]=pick([[1000,8,15],[500,4,20],[1000,10,10],[250,2,15],[500,6,20],[1000,12,15],[250,4,10],[120,2,60]]);return makeGtt({volume,hours,dropFactor})}},
    {key:'gtt-from-mlhr',label:'mL/hr → gtt/min',fields:[['rate','Pump rate (mL/hr)'],['dropFactor','Drop factor (gtt/mL)']],make:makeGttFromMlhr,random:()=>{const[rate,dropFactor]=pick([[100,15],[125,20],[150,10],[75,20],[80,15],[120,10],[60,60],[125,15]]);return makeGttFromMlhr({rate,dropFactor})}},
    {key:'mlhr-from-gtt',label:'gtt/min → mL/hr',fields:[['dropsPerMinute','Flow rate (gtt/min)'],['dropFactor','Drop factor (gtt/mL)']],make:makeMlhrFromGtt,random:()=>{const[dropsPerMinute,dropFactor]=pick([[25,15],[42,20],[20,10],[60,60],[30,15],[40,20],[15,10],[50,20]]);return makeMlhrFromGtt({dropsPerMinute,dropFactor})}},
    {key:'infusion-time',label:'Infusion duration',fields:[['volume','Volume (mL)'],['rate','Pump rate (mL/hr)']],make:makeDuration,random:()=>{const[volume,rate]=pick([[1000,125],[500,100],[250,125],[1000,100],[500,125],[250,100],[100,200],[500,80]]);return makeDuration({volume,rate})}}
  ];
  const byKey=Object.fromEntries(defs.map(d=>[d.key,d]));

  const typeList=document.querySelector('#type-list'),titleInput=document.querySelector('#quiz-title'),review=document.querySelector('#review'),questionList=document.querySelector('#question-list'),status=document.querySelector('#status'),publishStatus=document.querySelector('#publish-status'),approved=document.querySelector('#approved'),publish=document.querySelector('#publish');
  let draft=null,editing=null;
  typeList.innerHTML=defs.map((t,i)=>`<label><input type="checkbox" name="type" value="${t.key}" ${i===0?'checked':''}> ${t.label}</label>`).join('');

  const selectedTypes=()=>[...document.querySelectorAll('input[name="type"]:checked')].map(x=>x.value);
  const questionCount=()=>+(document.querySelector('input[name="count"]:checked')?.value||20);
  const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||`quiz-${Date.now()}`;
  function buildQuestion(keys,index){const available=defs.filter(t=>keys.includes(t.key));return available[index%available.length].random()}
  function resetApproval(message='Draft changed. Review approval reset.'){approved.checked=false;publish.disabled=true;publishStatus.textContent=message}
  function buildDraft(){const keys=selectedTypes();if(!keys.length){status.textContent='Choose at least one question type.';return}const count=questionCount(),ordered=shuffle(keys),questions=[];for(let n=0;n<count;n++)questions.push(buildQuestion(ordered,n));const title=titleInput.value.trim()||'Instructor Quiz';draft={version:1,id:slug(title),title,status:'draft',createdAt:new Date().toISOString(),questionCount:questions.length,questionTypes:[...new Set(keys)],questions};editing=null;approved.checked=false;publish.disabled=true;publishStatus.textContent='';status.textContent=`Draft created with ${questions.length} frozen questions.`;renderReview()}
  function renderReview(){if(!draft)return;review.hidden=false;document.querySelector('#review-title').textContent=draft.title;questionList.innerHTML=draft.questions.map((x,idx)=>{const def=byKey[x.key];const editor=editing===idx?`<div class="variable-editor"><h4>Set question variables</h4><div class="variable-grid">${def.fields.map(([name,label])=>`<label>${label}<input type="number" step="any" min="0.000001" data-var="${name}" value="${x.vars[name]}"></label>`).join('')}</div><p class="editor-error" data-editor-error></p><div class="editor-actions"><button class="primary" data-save="${idx}">Save variables</button><button class="secondary" data-random="${idx}">Randomize</button><button class="secondary" data-cancel="${idx}">Cancel</button></div></div>`:'';return `<article class="question-row"><div class="qnum">${idx+1}</div><div><p>${x.prompt}</p><div class="answer">${x.answer} ${x.unit}<span class="badge">${x.type}</span></div>${editor}</div><button class="secondary replace" data-replace="${idx}">Replace</button></article>`}).join('')}
  function openEditor(index){editing=index;renderReview()}
  function saveVariables(index){const x=draft.questions[index],def=byKey[x.key],row=questionList.querySelector(`[data-save="${index}"]`)?.closest('.variable-editor');if(!row)return;const vals={};let bad=false;def.fields.forEach(([name])=>{const v=Number(row.querySelector(`[data-var="${name}"]`).value);if(!Number.isFinite(v)||v<=0)bad=true;vals[name]=v});if(bad){row.querySelector('[data-editor-error]').textContent='Enter a number greater than 0 for every variable.';return}draft.questions[index]=def.make(vals);editing=null;resetApproval('Variables saved. Review approval reset.');renderReview()}
  function randomizeOne(index){const def=byKey[draft.questions[index].key];draft.questions[index]=def.random();editing=null;resetApproval('Question randomized. Review approval reset.');renderReview()}
  async function publishDraft(){if(!draft||!approved.checked)return;draft.status='published';draft.publishedAt=new Date().toISOString();publish.disabled=true;publishStatus.textContent='Publishing…';try{const res=await fetch('/instructor-api/instructor-quizzes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();publishStatus.textContent=`Published. Students can now open “${draft.title}”.`;if(data.id)draft.id=data.id}catch(err){draft.status='approved';const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${draft.id}.json`;a.click();URL.revokeObjectURL(url);publishStatus.textContent='Secure publish endpoint is not available yet, so the approved quiz JSON was downloaded instead.';publish.disabled=false}}

  document.querySelector('#generate').addEventListener('click',buildDraft);
  document.querySelector('#regenerate').addEventListener('click',buildDraft);
  document.querySelector('#clear').addEventListener('click',()=>{draft=null;editing=null;review.hidden=true;status.textContent='';publishStatus.textContent=''});
  questionList.addEventListener('click',e=>{let b=e.target.closest('[data-replace]');if(b)return openEditor(+b.dataset.replace);b=e.target.closest('[data-save]');if(b)return saveVariables(+b.dataset.save);b=e.target.closest('[data-random]');if(b)return randomizeOne(+b.dataset.random);b=e.target.closest('[data-cancel]');if(b){editing=null;renderReview()}});
  approved.addEventListener('change',()=>{publish.disabled=!approved.checked});
  publish.addEventListener('click',publishDraft);
})();
