(() => {
const app=document.querySelector('#app'); if(!app)return;
let mode='practice',difficulty='standard',length=10,qs=[],i=0,score=0,answered=false,selected=[];
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a};
const round=(n,p=1)=>{const f=10**p;return Math.round((n+Number.EPSILON)*f)/f};
const cases=(easy,standard,challenge)=>difficulty==='easy'?easy:difficulty==='challenge'?challenge:standard;
function q(type,prompt,answer,unit,formula,note,solution,tolerance=.05,answerMode='numeric',extra={}){return{type,prompt,answer,unit,formula,note,solution,tolerance,answerMode,...extra}}

function basicDose(){
  const c=pick(cases(
    [{drug:'acetaminophen',order:650,have:325,qty:1,unit:'tablets',route:'PO'},{drug:'amoxicillin',order:500,have:250,qty:5,unit:'mL',route:'PO'}],
    [{drug:'cephalexin',order:375,have:250,qty:5,unit:'mL',route:'PO'},{drug:'ondansetron',order:6,have:4,qty:2,unit:'mL',route:'IV'},{drug:'furosemide',order:35,have:20,qty:2,unit:'mL',route:'IV'}],
    [{drug:'amoxicillin',order:425,have:250,qty:5,unit:'mL',route:'PO'},{drug:'prednisone',order:27.5,have:10,qty:1,unit:'tablets',route:'PO'},{drug:'ondansetron',order:5.5,have:4,qty:2,unit:'mL',route:'IV'}]
  ));
  const a=round(c.order/c.have*c.qty,1);
  return q('Basic medication dose',`A patient has an order for ${c.drug} ${c.order} mg ${c.route}. Available: ${c.have} mg per ${c.qty} ${c.unit}. How many ${c.unit} should the nurse administer?`,a,c.unit,'Desired ÷ Have × Quantity = amount to give','Match the ordered dose to the concentration on hand.',`(${c.order} mg ÷ ${c.have} mg) × ${c.qty} ${c.unit} = ${a} ${c.unit}`,.06)
}

function weightDose(){
  const c=pick(cases(
    [{drug:'gentamicin',kg:70.5,dose:1.5,route:'IV q8h'},{drug:'acetaminophen',kg:24.5,dose:15,route:'PO per dose'}],
    [{drug:'enoxaparin',kg:83.7,dose:1,route:'subcutaneous q12h'},{drug:'clindamycin',kg:29.4,dose:10,route:'IV per dose'},{drug:'vancomycin',kg:56.8,dose:15,route:'IV per dose'}],
    [{drug:'gentamicin',kg:67.3,dose:1.7,route:'IV q8h'},{drug:'vancomycin',kg:61.7,dose:17.5,route:'IV per dose'},{drug:'clindamycin',kg:27.8,dose:12.5,route:'IV per dose'}]
  ));
  const a=round(c.kg*c.dose,1);
  return q('Weight-based dose',`A ${c.kg}-kg patient is prescribed ${c.drug} ${c.dose} mg/kg/dose ${c.route}. How many mg should the patient receive per dose?`,a,'mg','mg/kg/dose × kg = mg per dose','Multiply the ordered dose per kilogram by the patient’s measured weight.',`${c.dose} mg/kg × ${c.kg} kg = ${a} mg/dose`,.06)
}

const safeDoseCases={
  easy:[
    {drug:'cephalexin',kg:18.5,minDay:25,maxDay:50,freq:'q12h',doses:2,order:300,have:250,qty:5},
    {drug:'cephalexin',kg:22.5,minDay:25,maxDay:50,freq:'q12h',doses:2,order:200,have:250,qty:5},
    {drug:'cephalexin',kg:16.5,minDay:25,maxDay:50,freq:'q6h',doses:4,order:250,have:125,qty:5}
  ],
  standard:[
    {drug:'cephalexin',kg:18.7,minDay:25,maxDay:50,freq:'q12h',doses:2,order:275,have:250,qty:5},
    {drug:'cephalexin',kg:23.4,minDay:25,maxDay:50,freq:'q6h',doses:4,order:115,have:125,qty:5},
    {drug:'cephalexin',kg:31.6,minDay:25,maxDay:50,freq:'q12h',doses:2,order:425,have:250,qty:5},
    {drug:'cephalexin',kg:14.8,minDay:25,maxDay:50,freq:'q6h',doses:4,order:205,have:125,qty:5}
  ],
  challenge:[
    {drug:'cephalexin',kg:19.3,minDay:25,maxDay:50,freq:'q6h',doses:4,order:118,have:250,qty:5},
    {drug:'cephalexin',kg:27.9,minDay:25,maxDay:50,freq:'q12h',doses:2,order:705,have:250,qty:5},
    {drug:'cephalexin',kg:12.7,minDay:25,maxDay:50,freq:'q6h',doses:4,order:76,have:125,qty:5},
    {drug:'cephalexin',kg:33.4,minDay:25,maxDay:50,freq:'q12h',doses:2,order:405,have:250,qty:5}
  ]
};
function pediatricSafeRange(){
  const c=pick(safeDoseCases[difficulty]);
  const minDose=round(c.kg*c.minDay/c.doses,1),maxDose=round(c.kg*c.maxDay/c.doses,1);
  const safety=c.order<minDose?'low':c.order>maxDose?'high':'safe';
  const ml=round(c.order*c.qty/c.have,1);
  const safetyText=safety==='safe'?'within the recommended range':safety==='low'?'below the recommended range':'above the recommended range';
  const solution=`Recommended daily range: ${c.minDay}–${c.maxDay} mg/kg/day\n${c.minDay} × ${c.kg} = ${round(c.minDay*c.kg,1)} mg/day minimum\n${c.maxDay} × ${c.kg} = ${round(c.maxDay*c.kg,1)} mg/day maximum\nDivide by ${c.doses} doses/day: ${minDose}–${maxDose} mg/dose\nProvider ordered ${c.order} mg/dose — ${safetyText}.${safety==='safe'?`\n(${c.order} mg ÷ ${c.have} mg) × ${c.qty} mL = ${ml} mL`:''}`;
  return q('Pediatric safe-dose range',`A child weighs ${c.kg} kg. The provider orders ${c.drug} ${c.order} mg PO ${c.freq}. The recommended dose is ${c.minDay}–${c.maxDay} mg/kg/day in equally divided doses. Available: ${c.have} mg/${c.qty} mL. Is the ordered dose safe, too low, or too high?`,null,'','mg/kg/day × kg ÷ doses/day = safe mg/dose range','Calculate the minimum and maximum dose per administration before comparing the provider order. Only calculate mL if the order is within range.',solution,.06,'safety',{safety,amount:ml,amountUnit:'mL',minDose,maxDose})
}

const ivContexts=[['0.9% sodium chloride','maintenance IV fluid'],['lactated Ringer’s','replacement IV fluid'],['D5W','IV fluid'],['ceftriaxone','intermittent IV antibiotic'],['vancomycin','intermittent IV antibiotic']];
function contextLead(){const[name,kind]=pick(ivContexts);return `A patient is receiving ${name} as a ${kind}. `}
function mlhr(){const[v,h]=pick(cases([[1000,8],[500,4]],[[1000,7.5],[500,4.5],[250,2.25]],[[1000,7.25],[500,3.75],[250,1.8]]));const a=round(v/h,1);return q('mL/hr',`${contextLead()}Infuse ${v.toLocaleString()} mL over ${h} hours. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ hours = mL/hr','Divide total volume by infusion time.',`${v.toLocaleString()} mL ÷ ${h} hr = ${a} mL/hr`)}
function mlhrMin(){const[v,m,drug]=pick(cases([[100,30,'ceftriaxone'],[250,90,'vancomycin']],[[100,45,'metronidazole'],[250,105,'vancomycin'],[150,55,'clindamycin']],[[100,37,'ceftriaxone'],[250,83,'vancomycin'],[150,47,'clindamycin']]));const h=m/60,a=round(v/h,1);return q('Minutes → mL/hr',`A patient has an order for ${drug} in ${v} mL IV to infuse over ${m} minutes. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ (minutes ÷ 60) = mL/hr','Convert minutes to hours first.',`${m} min ÷ 60 = ${round(h,2)} hr\n${v} mL ÷ ${round(h,2)} hr = ${a} mL/hr`)}
function duration(){const[v,r,fluid]=pick(cases([[1000,125,'0.9% sodium chloride'],[500,100,'lactated Ringer’s']],[[1000,115,'0.9% sodium chloride'],[500,92,'lactated Ringer’s'],[250,108,'D5W']],[[1000,117,'0.9% sodium chloride'],[500,87,'lactated Ringer’s'],[250,113,'D5W']]));const a=round(v/r,2);return q('Infusion duration',`${fluid}, ${v.toLocaleString()} mL, is infusing at ${r} mL/hr. How many hours will the infusion take?`,a,'hours','mL ÷ mL/hr = hours','Divide volume by hourly rate.',`${v.toLocaleString()} mL ÷ ${r} mL/hr = ${a} hours`,.02)}
function completionTime(){const c=pick(cases([{start:'08:15',v:1000,r:125,fluid:'0.9% sodium chloride'}],[{start:'21:30',v:500,r:110,fluid:'lactated Ringer’s'},{start:'13:45',v:250,r:115,fluid:'ceftriaxone secondary infusion'}],[{start:'23:17',v:500,r:93,fluid:'D5 0.45% sodium chloride'},{start:'06:23',v:1000,r:117,fluid:'0.9% sodium chloride'}]));const[hh,mm]=c.start.split(':').map(Number),mins=Math.round(c.v/c.r*60),end=(hh*60+mm+mins)%(24*60),ans=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;return q('Completion time',`${c.fluid}, ${c.v} mL, is started at ${c.start} and infuses at ${c.r} mL/hr. Using 24-hour time, when will the infusion be complete?`,ans,'','start time + infusion duration = finish time','Calculate infusion duration, then add it to the start time.',`${c.v} mL ÷ ${c.r} mL/hr = ${round(c.v/c.r,2)} hr\nStart ${c.start} + ${mins} min = ${ans}`,0,'clock')}
function gtt(){const[v,h,d,fluid]=pick(cases([[1000,8,15,'0.9% sodium chloride'],[500,4,20,'lactated Ringer’s']],[[1000,7.5,15,'0.9% sodium chloride'],[500,5.5,20,'lactated Ringer’s'],[250,2.25,10,'D5W']],[[1000,7.25,15,'0.9% sodium chloride'],[500,4.75,20,'lactated Ringer’s'],[250,1.8,10,'D5W']]));const m=h*60,r=v*d/m,a=Math.round(r);return q('gtt/min',`A patient is prescribed ${fluid}, ${v.toLocaleString()} mL over ${h} hours. Tubing drop factor is ${d} gtt/mL. Calculate the gravity flow rate.`,a,'gtt/min','(mL × gtt/mL) ÷ minutes = gtt/min','Convert hours to minutes; round final answer to a whole drop.',`${h} hr × 60 = ${m} min\n(${v} × ${d}) ÷ ${m} = ${round(r,2)}\nRound = ${a} gtt/min`)}
function gttFromMlhr(){const[r,d,fluid]=pick(cases([[100,15,'0.9% sodium chloride'],[125,20,'lactated Ringer’s']],[[108,15,'0.9% sodium chloride'],[117,20,'lactated Ringer’s'],[83,10,'D5W']],[[113,15,'0.9% sodium chloride'],[127,20,'lactated Ringer’s'],[89,10,'D5W']]));const x=r*d/60,a=Math.round(x);return q('mL/hr → gtt/min',`${fluid} is infusing at ${r} mL/hr with tubing ${d} gtt/mL. What gravity flow rate should be set?`,a,'gtt/min','(mL/hr × gtt/mL) ÷ 60 = gtt/min','Convert hourly rate to drops per minute.',`(${r} × ${d}) ÷ 60 = ${round(x,2)}\nRound = ${a} gtt/min`)}
function mlhrFromGtt(){const[g,d,fluid]=pick(cases([[25,15,'0.9% sodium chloride'],[40,20,'lactated Ringer’s']],[[27,15,'0.9% sodium chloride'],[43,20,'lactated Ringer’s'],[19,10,'D5W']],[[31,15,'0.9% sodium chloride'],[47,20,'lactated Ringer’s'],[23,10,'D5W']]));const a=round(g*60/d,1);return q('gtt/min → mL/hr',`${fluid} is running at ${g} gtt/min using tubing ${d} gtt/mL. What is the equivalent infusion rate?`,a,'mL/hr','(gtt/min × 60) ÷ gtt/mL = mL/hr','Convert drops per minute to drops per hour, then divide by drop factor.',`(${g} × 60) ÷ ${d} = ${a} mL/hr`)}

function reconstitution(){const c=pick(cases([{drug:'ampicillin',order:500,conc:250}],[{drug:'cefazolin',order:825,conc:330},{drug:'methylprednisolone',order:75,conc:62.5}],[{drug:'cefazolin',order:775,conc:330},{drug:'methylprednisolone',order:87.5,conc:62.5}]));const a=round(c.order/c.conc,2);return q('Reconstitution',`After reconstitution, ${c.drug} is labeled ${c.conc} mg/mL. The order is ${c.order} mg. How many mL should the nurse draw up?`,a,'mL','ordered dose ÷ resulting concentration = mL to draw','Use the final concentration on the label.',`${c.order} mg ÷ ${c.conc} mg/mL = ${a} mL`,.03)}
function unitsHr(){const c=pick(cases([{drug:'heparin',order:1200,bagUnits:25000,bagMl:500},{drug:'regular insulin',order:4,bagUnits:100,bagMl:100}],[{drug:'heparin',order:1175,bagUnits:25000,bagMl:500},{drug:'regular insulin',order:5.5,bagUnits:100,bagMl:100}],[{drug:'heparin',order:1325,bagUnits:25000,bagMl:500},{drug:'regular insulin',order:7.3,bagUnits:100,bagMl:100}]));const conc=c.bagUnits/c.bagMl,a=round(c.order/conc,1);return q('Units/hr infusion',`A patient is receiving ${c.drug}. The order is ${c.order.toLocaleString()} units/hr. The IV contains ${c.bagUnits.toLocaleString()} units in ${c.bagMl} mL. What rate should the pump be set to?`,a,'mL/hr','ordered units/hr ÷ units/mL = mL/hr','Find units per mL, then divide the hourly order by the concentration.',`${c.bagUnits.toLocaleString()} ÷ ${c.bagMl} = ${round(conc,2)} units/mL\n${c.order} ÷ ${round(conc,2)} = ${a} mL/hr`,.06)}
function mcgMin(){const c=pick(cases([{drug:'nitroglycerin',order:20,bagMcg:50000,bagMl:250}],[{drug:'nitroglycerin',order:35,bagMcg:50000,bagMl:250}],[{drug:'nitroglycerin',order:47,bagMcg:50000,bagMl:250}]));const conc=c.bagMcg/c.bagMl,a=round(c.order*60/conc,1);return q('mcg/min infusion',`A patient has an order for ${c.drug} ${c.order} mcg/min. The IV contains ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. What pump rate is required?`,a,'mL/hr','(mcg/min × 60) ÷ mcg/mL = mL/hr','Convert minute dose to hourly dose, then divide by concentration.',`${c.order} × 60 = ${c.order*60} mcg/hr\n${c.bagMcg/c.bagMl} mcg/mL\n${c.order*60} ÷ ${c.bagMcg/c.bagMl} = ${a} mL/hr`,.06)}
function mcgKgMin(){const c=pick(cases([{drug:'dopamine',kg:70.5,order:5,bagMcg:400000,bagMl:250}],[{drug:'dopamine',kg:72.6,order:6.5,bagMcg:400000,bagMl:250},{drug:'dobutamine',kg:63.4,order:7.5,bagMcg:250000,bagMl:250}],[{drug:'dopamine',kg:68.7,order:7.3,bagMcg:400000,bagMl:250},{drug:'dobutamine',kg:61.9,order:8.2,bagMcg:250000,bagMl:250}]));const conc=c.bagMcg/c.bagMl,hourly=c.order*c.kg*60,a=round(hourly/conc,1);return q('mcg/kg/min infusion',`A ${c.kg}-kg patient is prescribed ${c.drug} ${c.order} mcg/kg/min. The IV contains ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. What rate should the pump be set to?`,a,'mL/hr','(mcg/kg/min × kg × 60) ÷ mcg/mL = mL/hr','Calculate the weight-based minute dose, convert to hourly, then divide by concentration.',`${c.order} × ${c.kg} × 60 = ${round(hourly,2)} mcg/hr\n${round(hourly,2)} ÷ ${round(conc,2)} = ${a} mL/hr`,.06)}
function amountHr(){const c=pick(cases([{drug:'magnesium sulfate',order:2,unit:'g',bag:20,bagMl:500}],[{drug:'magnesium sulfate',order:1.7,unit:'g',bag:20,bagMl:500},{drug:'amiodarone',order:55,unit:'mg',bag:450,bagMl:250}],[{drug:'magnesium sulfate',order:2.3,unit:'g',bag:20,bagMl:500},{drug:'amiodarone',order:67,unit:'mg',bag:450,bagMl:250}]));const conc=c.bag/c.bagMl,a=round(c.order/conc,1);return q(`${c.unit}/hr infusion`,`A patient is prescribed ${c.drug} ${c.order} ${c.unit}/hr. The IV contains ${c.bag} ${c.unit} in ${c.bagMl} mL. What pump rate is required?`,a,'mL/hr','ordered amount/hr ÷ amount/mL = mL/hr','Keep units matched.',`${c.bag} ÷ ${c.bagMl} = ${round(conc,4)} ${c.unit}/mL\n${c.order} ÷ ${round(conc,4)} = ${a} mL/hr`,.06)}
function meqMl(){const c=pick(cases([{drug:'potassium chloride',order:20,have:2}],[{drug:'potassium chloride',order:17.5,have:2},{drug:'sodium bicarbonate',order:37.5,have:1}],[{drug:'potassium chloride',order:23.5,have:2},{drug:'sodium bicarbonate',order:42.5,have:1}]));const a=round(c.order/c.have,1);return q('mEq to mL',`The provider orders ${c.drug} ${c.order} mEq. The vial contains ${c.have} mEq/mL. How many mL contain the ordered dose?`,a,'mL','ordered mEq ÷ mEq/mL = mL','Divide ordered mEq by concentration.',`${c.order} ÷ ${c.have} = ${a} mL`,.06)}
function dailyDivided(){const c=pick(cases([{drug:'cephalexin',kg:20.5,daily:25,freq:'q12h',doses:2}],[{drug:'cephalexin',kg:23.7,daily:37.5,freq:'q6h',doses:4},{drug:'amoxicillin',kg:18.6,daily:40,freq:'q8h',doses:3}],[{drug:'cephalexin',kg:27.3,daily:42.5,freq:'q6h',doses:4},{drug:'amoxicillin',kg:19.7,daily:40,freq:'q8h',doses:3}]));const daily=c.daily*c.kg,a=round(daily/c.doses,1);return q('Daily divided dose',`A ${c.kg}-kg patient is prescribed ${c.drug} ${c.daily} mg/kg/day divided ${c.freq}. How many mg should be given per dose?`,a,'mg','mg/kg/day × kg ÷ doses/day = mg per dose','Calculate total daily dose, then divide by doses/day.',`${c.daily} × ${c.kg} = ${round(daily,1)} mg/day\n${round(daily,1)} ÷ ${c.doses} = ${a} mg/dose`,.06)}

const types=[
['basic-dose','Basic medication dose',basicDose],['weight-dose','Weight-based dose',weightDose],['peds-safe-range','Pediatric safe-dose range',pediatricSafeRange],['mlhr-hours','mL/hr — hours',mlhr],['mlhr-minutes','mL/hr — minutes',mlhrMin],['infusion-time','Infusion duration',duration],['completion-time','Completion time',completionTime],['gtt-volume-time','gtt/min — volume + time',gtt],['gtt-from-mlhr','mL/hr → gtt/min',gttFromMlhr],['mlhr-from-gtt','gtt/min → mL/hr',mlhrFromGtt],['reconstitution','Reconstitution',reconstitution],['units-hour','Units/hr infusion',unitsHr],['mcg-minute','mcg/min infusion',mcgMin],['mcg-kg-minute','mcg/kg/min infusion',mcgKgMin],['amount-hour','mg/hr or g/hr infusion',amountHr],['meq-ml','mEq to mL',meqMl],['daily-divided','Daily divided dose',dailyDivided]
];
const formulas=[
['Basic medication dose','Desired ÷ Have × Quantity = amount to give','Use for tablets, liquids, and injectable volumes.'],['Weight-based dose','mg/kg/dose × kg = mg per dose','Use the measured weight in kilograms.'],['Pediatric safe-dose range','mg/kg/day × kg ÷ doses/day = safe mg/dose range','Compare the provider order with both ends of the range before calculating volume.'],['Pump rate — hours','mL ÷ hours = mL/hr','Divide total volume by infusion time.'],['Pump rate — minutes','mL ÷ (minutes ÷ 60) = mL/hr','Convert minutes to hours first.'],['Infusion duration','mL ÷ mL/hr = hours','Divide volume by hourly rate.'],['Completion time','start time + infusion duration = finish time','Carry across midnight when necessary.'],['Gravity flow','(mL × gtt/mL) ÷ minutes = gtt/min','Round final answer to a whole drop.'],['Known mL/hr → gtt/min','(mL/hr × gtt/mL) ÷ 60 = gtt/min','Round to a whole drop.'],['Known gtt/min → mL/hr','(gtt/min × 60) ÷ gtt/mL = mL/hr','Convert gravity rate to pump rate.'],['Reconstitution','ordered dose ÷ resulting concentration = mL to draw','Use final labeled concentration.'],['Units/hr infusion','ordered units/hr ÷ units/mL = mL/hr','Common heparin and insulin setup.'],['mcg/min infusion','(mcg/min × 60) ÷ mcg/mL = mL/hr','Convert minute dose to hourly dose first.'],['mcg/kg/min infusion','(mcg/kg/min × kg × 60) ÷ mcg/mL = mL/hr','Weight first, then convert to hourly dose.'],['mg/hr or g/hr infusion','ordered amount/hr ÷ amount/mL = mL/hr','Keep units matched.'],['mEq to mL','ordered mEq ÷ mEq/mL = mL','Electrolyte-volume calculation.'],['Daily divided dose','mg/kg/day × kg ÷ doses/day = mg per dose','q6h=4/day · q8h=3 · q12h=2 · q24h=1.']
];

function welcome(){app.innerHTML=`<h1 class="title">Dosage Calculations</h1><p class="subtitle">How do you want to study?</p><p class="copy">Choose exactly what you want to practice, combine several types, or let the app mix them for you.</p><div class="actions"><button class="text-action" data-a="formulas">Review formulas</button><button class="text-action submit" data-a="setup">Build a session</button></div>`}
function setup(){app.innerHTML=`<h1 class="title">Build a Session</h1><div class="setup"><section class="section"><h3>Mode</h3><div class="choice-row"><label class="choice"><input type="radio" name="mode" value="practice" checked>Practice</label><label class="choice"><input type="radio" name="mode" value="quiz">Quiz</label></div></section><section class="section"><h3>Difficulty</h3><div class="choice-row"><label class="choice"><input type="radio" name="difficulty" value="easy">Easy</label><label class="choice"><input type="radio" name="difficulty" value="standard" checked>Standard</label><label class="choice"><input type="radio" name="difficulty" value="challenge">Challenge</label></div><p class="note">All levels use realistic values. Difficulty changes how conveniently the numbers work out, not the clinical scenario.</p></section><section class="section"><h3>Question types</h3><div class="type-grid">${types.map(t=>`<label class="choice"><input type="checkbox" name="type" value="${t[0]}">${t[1]}</label>`).join('')}</div><button class="text-action" data-a="mix">Random mix</button></section><section class="section"><h3>Questions</h3><div class="choice-row">${[5,10,15,25].map(n=>`<label class="choice"><input type="radio" name="length" value="${n}" ${n===10?'checked':''}>${n}</label>`).join('')}</div></section></div><p id="msg" class="setup-message"></p><div class="actions"><button class="text-action" data-a="welcome">Back</button><button class="text-action submit" data-a="start">Start session</button></div>`}
function build(){const gens=shuffle(types.filter(t=>selected.includes(t[0]))),out=[];let c=0;while(out.length<length){if(c>=gens.length){c=0;gens.splice(0,gens.length,...shuffle(gens))}out.push(gens[c][2]());c++}return out}
function start(){selected=[...app.querySelectorAll('input[name="type"]:checked')].map(x=>x.value);if(!selected.length){app.querySelector('#msg').textContent='Choose at least one question type, or select Random mix.';return}mode=app.querySelector('input[name="mode"]:checked')?.value||'practice';difficulty=app.querySelector('input[name="difficulty"]:checked')?.value||'standard';length=+app.querySelector('input[name="length"]:checked')?.value||10;qs=build();i=0;score=0;renderQ()}
function parseAnswer(s){const m=s.trim().match(/^(-?\d+(?:\.\d+)?)\s*(.*)$/);if(!m)return null;return{n:+m[1],u:m[2].trim().toLowerCase().replace(/\s+/g,'')}}
function normUnit(u){return u.replace('ml/hour','ml/hr').replace('mlhr','ml/hr').replace('gtt/minute','gtt/min').replace('gttmin','gtt/min').replace('hrs','hours').replace(/^hr$/,'hours').replace(/^tablet$/,'tablets')}
function normClock(s){const x=s.trim().replace(/\s+/g,''),m=x.match(/^(\d{1,2}):?(\d{2})$/);if(!m)return null;const h=+m[1],min=+m[2];if(h>23||min>59)return null;return `${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
function renderQ(){answered=false;const x=qs[i];let answerArea;if(x.answerMode==='safety'){answerArea=`<div class="safety-choices"><button class="text-action safety-choice" data-safe="safe">Safe</button><button class="text-action safety-choice" data-safe="low">Too low</button><button class="text-action safety-choice" data-safe="high">Too high</button></div><div id="safety-next"></div>`}else{const placeholder=x.answerMode==='clock'?'Type 24-hour time, e.g. 16:30':'Type answer with unit, e.g. 4.7 mL';answerArea=`<div class="answer-row"><input id="answer" class="answer-input" autocomplete="off" placeholder="${placeholder}"><button class="text-action submit" data-a="submit">Submit</button></div>`}app.innerHTML=`<div class="meta"><span>${mode==='practice'?'Practice':'Quiz'} · ${difficulty[0].toUpperCase()+difficulty.slice(1)} · Question ${i+1} of ${length}</span><span>${x.type}</span></div><div class="problem">${x.prompt}</div>${answerArea}${mode==='practice'?`<div class="actions"><button class="text-action" data-a="hint">See formula</button></div><div id="hint"></div>`:''}<div id="feedback"></div>`;app.querySelector('#answer')?.focus()}
function correctAnswerText(x){if(x.answerMode==='safety'){const label=x.safety==='safe'?'Safe':x.safety==='low'?'Too low':'Too high';return x.safety==='safe'&&Number.isFinite(x.amount)?`${label} — ${x.amount} ${x.amountUnit||'mL'}`:label}if(x.answerMode==='clock')return x.answer;return `${x.answer} ${x.unit}`.trim()}
function finishQuestion(ok,x){answered=true;if(ok)score++;const f=app.querySelector('#feedback'),solution=x.solution.replace(/\n/g,'<br>');f.innerHTML=`<div class="feedback ${ok?'correct':'incorrect'}"><h3>${ok?'Correct':'Incorrect'}</h3><div class="solution"><b>Correct answer:</b> ${correctAnswerText(x)}</div><div class="formula-help"><b>Formula:</b> ${x.formula}</div><div class="solution">${solution}</div><div class="actions"><button class="text-action submit" data-a="next">${i+1<length?'Next question':'See results'}</button></div></div>`}
function submitSafety(choice){if(answered)return;const x=qs[i];if(choice!==x.safety){finishQuestion(false,x);return}if(choice!=='safe'){finishQuestion(true,x);return}const box=app.querySelector('#safety-next');box.innerHTML=`<div class="feedback correct"><b>Safe.</b> The order is within ${x.minDose}–${x.maxDose} mg/dose. Now calculate the amount to administer.</div><div class="answer-row"><input id="answer" class="answer-input" autocomplete="off" placeholder="Type answer with unit, e.g. 5.5 mL"><button class="text-action submit" data-a="submit-safety-amount">Submit</button></div>`;app.querySelectorAll('.safety-choice').forEach(b=>b.disabled=true);app.querySelector('#answer').focus()}
function submit(){if(answered)return;const x=qs[i],raw=app.querySelector('#answer')?.value||'';let ok=false;if(x.answerMode==='clock'){const val=normClock(raw);if(!val){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a valid 24-hour time.</div>';return}ok=val===x.answer}else{const p=parseAnswer(raw);if(!p){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a number and the unit.</div>';return}ok=normUnit(p.u)===normUnit(x.unit.toLowerCase().replace(/\s+/g,''))&&Math.abs(p.n-x.answer)<=x.tolerance}finishQuestion(ok,x)}
function submitSafetyAmount(){if(answered)return;const x=qs[i],p=parseAnswer(app.querySelector('#answer')?.value||'');if(!p){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a number and the unit.</div>';return}const ok=normUnit(p.u)===normUnit(x.amountUnit.toLowerCase())&&Math.abs(p.n-x.amount)<=x.tolerance;finishQuestion(ok,x)}
function next(){i++;if(i>=length)results();else renderQ()}
function results(){const pct=Math.round(score/length*100);app.innerHTML=`<div class="results"><h1 class="title">Session Complete</h1><div class="score">${score}/${length}</div><p class="subtitle">${pct}%</p><div class="actions" style="justify-content:center"><button class="text-action" data-a="setup">Build another session</button><a class="text-action" href="index.html">Home</a></div></div>`}
function showFormulas(page=0){const perPage=9,pages=Math.ceil(formulas.length/perPage),slice=formulas.slice(page*perPage,page*perPage+perPage);app.innerHTML=`<h1 class="title">Formula Review · ${page+1} of ${pages}</h1><div class="formula-grid">${slice.map(x=>`<section class="formula-item"><h3>${x[0]}</h3><div class="equation">${x[1]}</div><p>${x[2]}</p></section>`).join('')}</div><nav class="nav">${page?'<button class="text-action" data-a="fprev">← Previous</button>':'<span></span>'}<button class="text-action" data-a="welcome">Back</button>${page<pages-1?'<button class="text-action" data-a="fnext">Next →</button>':'<span></span>'}</nav>`;app.dataset.formulaPage=page}
app.addEventListener('click',e=>{const safety=e.target.closest('[data-safe]');if(safety){submitSafety(safety.dataset.safe);return}const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='welcome')welcome();if(a==='setup')setup();if(a==='mix'){app.querySelectorAll('input[name="type"]').forEach(x=>x.checked=true);app.querySelector('#msg').textContent='Random mix selected — all available types are included.'}if(a==='start')start();if(a==='submit')submit();if(a==='submit-safety-amount')submitSafetyAmount();if(a==='next')next();if(a==='hint'){const x=qs[i];app.querySelector('#hint').innerHTML=`<div class="formula-help"><b>${x.formula}</b><div class="small">${x.note}</div></div>`}if(a==='formulas')showFormulas(0);if(a==='fprev')showFormulas(Math.max(0,(+app.dataset.formulaPage||0)-1));if(a==='fnext')showFormulas((+app.dataset.formulaPage||0)+1)});
app.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='answer'){e.preventDefault();qs[i]?.answerMode==='safety'?submitSafetyAmount():submit()}});
if(location.hash==='#formulas')showFormulas(0);else setup();
})();
