(() => {
const app=document.querySelector('#app');if(!app)return;const E=window.DosageEngine;if(!E)throw new Error('DosageEngine not loaded');
let mode='practice',difficulty='standard',length=10,qs=[],i=0,score=0,answered=false,selected=[];
const shuffle=a=>{a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a};
const fingerprint=x=>`${x.key}|${String(x.prompt).toLowerCase().replace(/\s+/g,' ').trim()}`;
function welcome(){app.innerHTML=`<h1 class="title">Dosage Calculations</h1><p class="subtitle">How do you want to study?</p><p class="copy">Choose exactly what you want to practice, combine several types, or let the app mix them for you.</p><div class="actions"><button class="text-action" data-a="formulas">Review formulas</button><button class="text-action submit" data-a="setup">Build a session</button></div>`}
function setup(){app.innerHTML=`<h1 class="title">Build a Session</h1><div class="setup"><section class="section"><h3>Mode</h3><div class="choice-row"><label class="choice"><input type="radio" name="mode" value="practice" checked>Practice</label><label class="choice"><input type="radio" name="mode" value="quiz">Quiz</label></div></section><section class="section"><h3>Difficulty</h3><div class="choice-row"><label class="choice"><input type="radio" name="difficulty" value="easy">Easy</label><label class="choice"><input type="radio" name="difficulty" value="standard" checked>Standard</label><label class="choice"><input type="radio" name="difficulty" value="challenge">Challenge</label></div><p class="note">Difficulty changes how conveniently the numbers work out, not the clinical logic.</p></section><section class="section"><h3>Question types</h3><div class="type-grid">${E.types.map(t=>`<label class="choice"><input type="checkbox" name="type" value="${t.key}">${t.label}</label>`).join('')}</div><button class="text-action" data-a="mix">Random mix</button></section><section class="section"><h3>Questions</h3><div class="choice-row">${[5,10,15,25].map(n=>`<label class="choice"><input type="radio" name="length" value="${n}" ${n===10?'checked':''}>${n}</label>`).join('')}</div></section></div><p id="msg" class="setup-message"></p><div class="actions"><button class="text-action" data-a="welcome">Back</button><button class="text-action submit" data-a="start">Start session</button></div>`}
function build(){const keys=shuffle(selected),out=[],used=new Set();for(let n=0;n<length;n++){const key=keys[n%keys.length];let x=null;for(let a=0;a<500;a++){const candidate=E.generate(key,difficulty);if(!used.has(fingerprint(candidate))){x=candidate;break}}if(!x)x=E.generate(key,difficulty);used.add(fingerprint(x));out.push(x)}return out}
function start(){selected=[...app.querySelectorAll('input[name="type"]:checked')].map(x=>x.value);if(!selected.length){app.querySelector('#msg').textContent='Choose at least one question type, or select Random mix.';return}mode=app.querySelector('input[name="mode"]:checked')?.value||'practice';difficulty=app.querySelector('input[name="difficulty"]:checked')?.value||'standard';length=+app.querySelector('input[name="length"]:checked')?.value||10;qs=build();i=0;score=0;renderQ()}
function parseAnswer(s){const m=s.trim().match(/^(-?\d+(?:\.\d+)?)\s*(.*)$/);if(!m)return null;return{n:+m[1],u:m[2].trim().toLowerCase().replace(/\s+/g,'')}}
function normUnit(u){return u.replace('ml/hour','ml/hr').replace('mlhr','ml/hr').replace('gtt/minute','gtt/min').replace('gttmin','gtt/min').replace('hrs','hours').replace(/^hr$/,'hours').replace(/^tablet$/,'tablets').replace(/^mg$/,'mg').replace('mg/dose','mg')}
function normClock(s){const x=s.trim().replace(/\s+/g,''),m=x.match(/^(\d{1,2}):?(\d{2})$/);if(!m)return null;const h=+m[1],min=+m[2];if(h>23||min>59)return null;return `${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
function safetyCode(x){return x.answer==='safe'?'safe':x.answer==='too low'?'low':'high'}
function renderQ(){answered=false;const x=qs[i],isSafety=x.key==='peds-safe-range',isClock=x.key==='completion-time';let area;if(isSafety){area=`<div class="safety-choices"><button class="text-action safety-choice" data-safe="safe">Safe</button><button class="text-action safety-choice" data-safe="low">Too low</button><button class="text-action safety-choice" data-safe="high">Too high</button></div><div id="safety-next"></div>`}else{area=`<div class="answer-row"><input id="answer" class="answer-input" autocomplete="off" placeholder="${isClock?'Type 24-hour time, e.g. 16:30':'Type answer with unit, e.g. 4.7 mL'}"><button class="text-action submit" data-a="submit">Submit</button></div>`}app.innerHTML=`<div class="meta"><span>${mode==='practice'?'Practice':'Quiz'} · ${difficulty[0].toUpperCase()+difficulty.slice(1)} · Question ${i+1} of ${length}</span><span>${x.type}</span></div><div class="problem">${x.prompt}</div>${area}${mode==='practice'?`<div class="actions"><button class="text-action" data-a="hint">See formula</button></div><div id="hint"></div>`:''}<div id="feedback"></div>`;app.querySelector('#answer')?.focus()}
function answerText(x){if(x.key==='peds-safe-range'){const label=x.answer==='safe'?'Safe':x.answer==='too low'?'Too low':'Too high';return label}return `${x.answer}${x.unit?` ${x.unit}`:''}`}
function finishQuestion(ok,x,extra=''){answered=true;if(ok)score++;app.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'correct':'incorrect'}"><h3>${ok?'Correct':'Incorrect'}</h3><div class="solution"><b>Correct answer:</b> ${answerText(x)}${extra}</div><div class="formula-help"><b>Formula:</b> ${x.formula}</div><div class="solution">${String(x.solution).replace(/\n/g,'<br>')}</div><div class="actions"><button class="text-action submit" data-a="next">${i+1<length?'Next question':'See results'}</button></div></div>`}
function submitSafety(choice){if(answered)return;const x=qs[i],correct=safetyCode(x);if(choice!==correct){finishQuestion(false,x);return}if(correct!=='safe'){finishQuestion(true,x);return}const v=x.vars||{},box=app.querySelector('#safety-next');box.innerHTML=`<div class="feedback correct"><b>Safe.</b> The order is within ${v.min}–${v.max} mg/dose. Now calculate the amount to administer.</div><div class="answer-row"><input id="answer" class="answer-input" autocomplete="off" placeholder="Type answer with unit, e.g. 5.5 mL"><button class="text-action submit" data-a="submit-safety-amount">Submit</button></div>`;app.querySelectorAll('.safety-choice').forEach(b=>b.disabled=true);app.querySelector('#answer').focus()}
function submit(){if(answered)return;const x=qs[i],raw=app.querySelector('#answer')?.value||'';let ok=false;if(x.key==='completion-time'){const val=normClock(raw);if(!val){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a valid 24-hour time.</div>';return}ok=val===x.answer}else{const p=parseAnswer(raw);if(!p){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a number and the unit.</div>';return}const expected=normUnit(String(x.unit||'').toLowerCase().replace(/\s+/g,''));ok=normUnit(p.u)===expected&&Math.abs(p.n-Number(x.answer))<=x.tolerance}finishQuestion(ok,x)}
function submitSafetyAmount(){if(answered)return;const x=qs[i],v=x.vars||{},p=parseAnswer(app.querySelector('#answer')?.value||'');if(!p){app.querySelector('#feedback').innerHTML='<div class="feedback incorrect">Enter a number and the unit.</div>';return}const ok=normUnit(p.u)==='ml'&&Math.abs(p.n-v.ml)<=.06;finishQuestion(ok,x,` — ${v.ml} mL`)}
function next(){i++;if(i>=length)results();else renderQ()}
function results(){const pct=Math.round(score/length*100);app.innerHTML=`<div class="results"><h1 class="title">Session Complete</h1><div class="score">${score}/${length}</div><p class="subtitle">${pct}%</p><div class="actions" style="justify-content:center"><button class="text-action" data-a="setup">Build another session</button><a class="text-action" href="index.html">Home</a></div></div>`}
function showFormulas(page=0){const perPage=9,pages=Math.ceil(E.formulaReview.length/perPage),slice=E.formulaReview.slice(page*perPage,page*perPage+perPage);app.innerHTML=`<h1 class="title">Formula Review · ${page+1} of ${pages}</h1><div class="formula-grid">${slice.map(x=>`<section class="formula-item"><h3>${x[0]}</h3><div class="equation">${x[1]}</div></section>`).join('')}</div><nav class="nav">${page?'<button class="text-action" data-a="fprev">← Previous</button>':'<span></span>'}<button class="text-action" data-a="welcome">Back</button>${page<pages-1?'<button class="text-action" data-a="fnext">Next →</button>':'<span></span>'}</nav>`;app.dataset.formulaPage=page}
app.addEventListener('click',e=>{const s=e.target.closest('[data-safe]');if(s){submitSafety(s.dataset.safe);return}const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='welcome')welcome();if(a==='setup')setup();if(a==='mix'){app.querySelectorAll('input[name="type"]').forEach(x=>x.checked=true);app.querySelector('#msg').textContent='Random mix selected — all available types are included.'}if(a==='start')start();if(a==='submit')submit();if(a==='submit-safety-amount')submitSafetyAmount();if(a==='next')next();if(a==='hint'){const x=qs[i];app.querySelector('#hint').innerHTML=`<div class="formula-help"><b>${x.formula}</b><div class="small">${x.note}</div></div>`}if(a==='formulas')showFormulas(0);if(a==='fprev')showFormulas(Math.max(0,(+app.dataset.formulaPage||0)-1));if(a==='fnext')showFormulas((+app.dataset.formulaPage||0)+1)});
app.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='answer'){e.preventDefault();qs[i]?.key==='peds-safe-range'?submitSafetyAmount():submit()}});
if(location.hash==='#formulas')showFormulas(0);else setup();
})();